### ISSUE TITLE
Nix 2.4 changed escaping

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#1000]
Change is not documented.

https://github.com/haskell-nix/hnix/runs/4081568140?check_suite_focus=true

```
   Eval comparison tests
    ind-string-14.nix:                                               FAIL (0.02s)
      tests/TestCommon.hs:68:
      tests/eval-compare/ind-string-14.nix
      expected: "\"Escaping of ' followed by ': ''\\nEscaping of $ followed by {: \\${\\nAnd finally to interpret \\\\n etc. as in a string: \\n, \\r, \\t.\\n\"\n"
       but got: "\"Escaping of ' followed by ': ''\\nEscaping of $ followed by {: ${\\nAnd finally to interpret \\\\n etc. as in a string: \\n, \\r, \\t.\\n\"\n"
      Use -p '/ind-string-14.nix/' to rerun this test only
      
      tests/TestCommon.hs:68:
      tests/eval-compare/ind-string-05.nix
      expected: "\"  The \\\\ is not special here.\\n' can be followed by any character except another ', e.g. 'x'.\\nLikewise for $, e.g. $$ or $varName.\\nBut ' followed by ' is special, as is $ followed by {.\\nIf you want them, use anti-quotations: '', \\${.\\n\"\n"
       but got: "\"  The \\\\ is not special here.\\n' can be followed by any character except another ', e.g. 'x'.\\nLikewise for $, e.g. $$ or $varName.\\nBut ' followed by ' is special, as is $ followed by {.\\nIf you want them, use anti-quotations: '', ${.\\n\"\n"
      Use -p '/ind-string-05.nix/' to rerun this test only.
```

**Comment by Anton-Latukha** [comment]
We hit #1000.

Recently I was doing a lot of work.
& now suddenly upstream changes breakages piled on.

I would rest & work at my own pace.

Anybody who wants can take this.

**Comment by Anton-Latukha** [comment]
Report is a part of the #996

**Comment by Anton-Latukha** [comment]
Seems like this function: https://github.com/NixOS/nix/blob/02dff9e5299eccd8199dfbf1b5c20bf6ed9f07bd/src/nix/get-env.sh#L104

**Comment by Anton-Latukha** [comment]
It is probably some change regarding `Nix.Parser : nixString' :: Parser (NString NExprLoc)`

HNix code is complex. But complex in a much better meaning.

It happened between Nix `git diff 2.3.15..2.4`, if it is not: https://github.com/NixOS/nix/blob/02dff9e5299eccd8199dfbf1b5c20bf6ed9f07bd/src/nix/get-env.sh#L104 and not `shellEscape` - then *idk* the place currently.

Also - if it is not in diff or in git logs - it is probably an upstream bug.

**Comment by Anton-Latukha** [comment]
Nope.

It should be just a representation.

But also there are some other changes. Nix did not change the official semantic version of the language, but breakages are there.

It is time to open #610 & sort them out.

**Comment by Anton-Latukha** [comment]
Seems it still requires the change at least in Parser.

And somewhere else, maybe/probably in `prettyString`.

So far I not understood what is happening with escaping there.

**Comment by Anton-Latukha** [comment]
Nope, again.

Understood the parser part - it does escape `''${`, but Nix changed the representation of it to `\\{$`, so... So far I do not have idea where it should be placed.

**Comment by soulomoon** [comment]
> Nope, again.
> 
> Understood the parser part - it does escape `''${`, but Nix changed the representation of it to `\\{$`, so... So far I do not have idea where it should be placed.

Both the printer in hnix binary `prettyNix` and the printer in nix-instantiate escape `$` as `\$`, but not for `printNix` in hnix-tests(`assertEvalFileMatchesNix` to be specific). Maybe the printer in the test should be revised to escape `$` as well.

**Comment by soulomoon** [comment]
> Nope, again.
> 
> Understood the parser part - it does escape `''${`, but Nix changed the representation of it to `\\{$`, so... So far I do not have idea where it should be placed.

Awkward situation here, string escape.
* hnix: `$` -> `\$`, `${` -> `\${`
* nix-instantiate: `$` -> `$`, `${` -> `\${`
* hnix-tests: `$` -> `$`, `${` -> `${`

**Comment by soulomoon** [comment]
It is related to nix [4012 issue here](https://github.com/NixOS/nix/pull/4012)

explicitly formatting `${` to `\${`
`else if (*i == '$' && *(i+1) == '{') str << "\\" << *i;`

If hnix decide to follow the [nix 4012](https://github.com/NixOS/nix/pull/4012) behavior, 
I have gone through the related code in hnix and nix and I am willing to take this and make a pull request for it.

**Comment by Anton-Latukha** [comment]
I would be thankful for it.

---

<sub>

P.S. In the nearest time I would also attend to other accumulated reports & ship `1.4` support release & `1.6` major release.

**Comment by soulomoon** [comment]
> I would be thankful for it.
> 
> P.S. In the nearest time I would also attend to other accumulated reports & ship `1.4` support release & `1.6` major release.

#1019  have been made.
It seems we have to bumped up the nix version in the submodule to make everything compatible.

The eval-okay-ind-string.exp contains relevant expected test result and the version in the submodule is outdated

P.S. I am still very new to hnix, hope that I am helping.

**Comment by Anton-Latukha** [comment]
Considering this closed.

If things pop-up, a special report would work better.

And we still need to release this.
