### ISSUE TITLE
Build failure in `hnix-0.14.0.2` with `aeson-1.5.6.0`

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#1001]
```
src/Nix/Utils.hs:163:11: error:
    Not in scope: ‘HM.toList’
    Perhaps you meant one of these:
      ‘M.toList’ (imported from Data.HashMap.Lazy),
      ‘V.toList’ (imported from Data.Vector)
    No module named ‘HM’ is imported.
    |
163 |           HM.toList
    |           ^^^^^^^^^
cabal: Failed to build hnix-0.14.0.2 
```

**Comment by Anton-Latukha** [comment]
Woop woop woop...

Sorry for this. Was backporting a JSON function that is now in JSON module.

Already released `0.14.0.3`.

**Comment by sjakobi** [comment]
Thanks for the quick response, @Anton-Latukha! :)

I've revised v0.14.0.2 to prevent builds with `aeson < 2`: https://hackage.haskell.org/package/hnix-0.14.0.2/revisions/

**Comment by sjakobi** [comment]
Unfortunately it seems that v0.14.0.3 is broken too:

```
src/Nix/Utils.hs:18:1: error:
    Could not load module ‘Data.HashMap’
    It is a member of the hidden package ‘hashmap-1.3.3’.
    Perhaps you need to add ‘hashmap’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘hashmap-1.3.3’.
    Perhaps you need to add ‘hashmap’ to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
18 | import qualified Data.HashMap                  as HM
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by sjakobi** [comment]
`unordered-containers` doesn't expose `Data.HashMap`. You want `Data.HashMap.Lazy` or `Data.HashMap.Strict`.

**Comment by Anton-Latukha** [comment]
Well, yes, again.

I hope backpack arrives soon.

Rarely do I want to cut corners, but the real world corrects me every time.

Hope I learned the lesson.

There is not much that needs to be done. Good if there was a tool to test backward compatibility with old version of a package. But also temporarily manually restricting the bounds helps.

**Comment by sjakobi** [comment]
I have some bad news for you:

```
src/Nix/Effects/Basic.hs:16:1: error:
    Could not find module ‘Prettyprint’
    Perhaps you meant
      Prettyprinter (needs flag -package-id prettyprinter-1.7.0)
      Prettyprinter (from prettyprinter-1.7.1)
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
16 | import           Prettyprint                    ( fillSep )
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build hnix-0.14.0.4
```

I recommend using `cabal`'s `--constraint` flag, e.g. `cabal build hnix --constraint 'aeson < 2'`.

**Comment by sjakobi** [comment]
In the case of `v0.14.0.4` I don't see how the package would have compiled with any build plan. Please use CI or some basic testing, and don't upload such broken releases to Hackage.

**Comment by Anton-Latukha** [comment]
Yes.
It is largely because I am tired, experimenting with a direct push into the support branch & lazy to pass the CI. Seems to not work great 8]

Well, actually, yes - I've could open the PR just into the support branch, not thought about it. Because before actually never did/really needed to support old version branch before.

I ran the build test & it seemed to pass, or I did something, maybe terminated early. Just impatient & tired.

Now on docs upload, I am getting:
```
cabal: '/usr/bin/curl' exited with an error:
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```

Since I was automating doc upload at the same time - maybe Hackage has tight connection/upload quotas, maybe anything else.

The new version passes the test suite.

So docs would be tomorrow.

**Comment by sjakobi** [comment]
No idea about the `curl` error, I'm afraid.

But at least I'm getting a clean build with `hnix-0.14.0.5`.

Please note that I've made a revision for v0.14.0.3 (https://hackage.haskell.org/package/hnix-0.14.0.3/revisions/), and that I've marked v0.14.0.4 as deprecated.

I hope you get a good rest! :)

**Comment by Anton-Latukha** [comment]
Yes.

Thank you.

That was not great.

**Comment by sjakobi** [comment]
I've revised v0.14.0.4 with a bound `base < 0` so it doesn't show up in build plans any more: https://hackage.haskell.org/package/hnix-0.14.0.4/revisions/
