### ISSUE TITLE
Lexical scoping takes precedence over `with`

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#104]
in [eval-okay-with.nix](data/nix/tests/lang/eval-okay-with.nix), we currently look up variables in the nearest enclosing scope, regardless of whether it is a `with` scope or a lexical scope.  Instead, we should only use the `with` scope if a lexical lookup fails.

**Comment by jwiegley** [comment]
Related part of the Nix manual:

> The bindings introduced by with do not shadow bindings introduced by other means, e.g.

    let a = 3; in with { a = 1; }; let a = 4; in with { a = 2; }; ...

> establishes the same scope as

    let a = 1; in let a = 2; in let a = 3; in let a = 4; in ...
