### ISSUE TITLE
Refactor: change PatternSynonyms in value module from Unidirectional to bidirectional

### ISSUE THREAD

**Issue by soulomoon** [haskell-nix/hnix#1045]
In `Value.hs`
It is really cool to have the correspondence between nix and haskell.

These are how the conversion between nix and haskell currently are.

* Value constructor, `mkNV*`.
* Value destructor unidirectional PatternSynonyms, `NV*`.  

But it seems superfluous since these two can actually be merged together by switching the PatternSynonyms from unidirectional to bidirectional.
We would have unified constructor and destructor for values.

* pros, cleaner, coherent, shorter, easier to go through the code.
* cons, We now need both constraints in PatternSynonyms from each of the two parts, `(Comonad f, Applicative f)` to make it work.

I have a working draft here #1046, hope you guys could review it and give advices.

**Comment by Anton-Latukha** [comment]
It poped up in discussions in the past.

I've not yet internalized the design semantics of all types of PatternSynonyms application in the code, but probably it is just the time to do so.

Liking the result in #1046.

**Comment by soulomoon** [comment]
work is done for bidirectional patterns
