### ISSUE TITLE
hnix-0.16 has too strict bounds 

### ISSUE THREAD

**Issue by sternenseemann** [haskell-nix/hnix#1083]
Building from hackage I run into

```
base >=4.12 && <4.16,
logict >=0.6.0 && <0.7 || >=0.7.0.2 && <0.8,
optparse-applicative >=0.14.3 && <0.17,
relude >=1.0.0 && <1.1.0,
template-haskell >=2.13 && <2.18,
time >=1.8.0 && <1.9 || >=1.9.3 && <1.10
`````
But building with `base-4.16.*`,  `logict-0.8.0.0`, `optparse-applicative-0.17.0.0.drv`, `relude-1.1.0.0`, `time-1.11.*`, `template-haskell-2.18.0.0`  seems to be possible.

A hackage revision would be neat, but I'll work around this with `doJailbreak`  for now, I guess the bounds are updated on `master`  (what is the state of 0.17 anyways?).

**Comment by andreabedini** [comment]
@haskell-nix I see the bounds have already been bumped on master, can we have a revision on hackage please?

**Comment by ners** [comment]
I've cut a new release here: https://github.com/haskell-nix/hnix/pull/1092
