### ISSUE TITLE
XML support

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#109]
These tests can't be run because we don't yet support Nix's XML serialization format:

- [x] eval-okay-xml
- [x] eval-okay-toxml2
- [x] eval-okay-toxml
- [x] eval-okay-functionargs
- [ ] eval-okay-closure

**Comment by jwiegley** [comment]
`eval-okay-closure` is going to need its own issue, since it requires implementing `builtins.genericClosure`.

**Comment by mightybyte** [comment]
I'll take a stab at `eval-okay-xml`.

**Comment by mightybyte** [comment]
`eval-okay-xml` and `eval-okay-functionargs` are now passing.

**Comment by ryantrinkle** [comment]
Nice!

**Comment by jwiegley** [comment]
See #144 for the remaining part.
