### ISSUE TITLE
Release 0.17.0 to hackage

### ISSUE THREAD

**Issue by locallycompact** [haskell-nix/hnix#1096]
Hi could we get a release of 0.17.0 to hackage please?

**Comment by sorki** [comment]
Please be patient. If Anton can't make it, we could escalate to John Wiegley but I'm intentionally not pinging either of them for now.

**Comment by Anton-Latukha** [comment]
Thank you for being patient.

I wanted to carve the release. Currently have only NixOS dev env accessible & got a linker bug in Haskell packages, solved it. Have access to Hackage account, which is most important, and going to do the release today or the next day.

Thank you all.

**Comment by Anton-Latukha** [comment]
Release [`0.17.0` uploaded on Hackage](https://hackage.haskell.org/package/hnix-0.17.0), but without Hackage docs.

In my dev env Haddock generation keeps aborting:
```
Error: cabal: Failed to build documentation for basement-0.0.16 (which is
required by hnix-0.17.0).
Failed to build documentation for prettyprinter-1.7.1 (which is required by
hnix-0.17.0).
```
