### ISSUE TITLE
Upload haddocks to Hackage for 0.17.0

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#1099]
Currently can not generate Haddocks:
In my nix-shell dev env Haddock generation keeps aborting:
```
Error: cabal: Failed to build documentation for basement-0.0.16 (which is
required by hnix-0.17.0).
Failed to build documentation for prettyprinter-1.7.1 (which is required by
hnix-0.17.0).
```

**Comment by sorki** [comment]
Probably due to GHC8.10.7, https://github.com/haskell-nix/hnix/pull/1100 fixes that

**Comment by Anton-Latukha** [comment]
Probably you uploaded the docs, thank you.

**Comment by sorki** [comment]
> Probably you uploaded the docs, thank you.

Wasn't me :wink: Thanks for the release!
