### ISSUE TITLE
builtins.tryEval

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#110]
See [Builtins](https://nixos.org/nix/manual/#ssec-builtins).

`MonadFramed` already has a [`throwError`](https://github.com/jwiegley/hnix/blob/735c5ca15ab2beb09a51d7551d5e362bbbbc5793/Nix/Stack.hs#L55-L59) function, but it doesn't have a `catchError`.  We need to write `catchError` and then add a builtin [here](https://github.com/jwiegley/hnix/blob/735c5ca15ab2beb09a51d7551d5e362bbbbc5793/Nix/Builtins.hs#L133) that exposes it.

This unblocks these tests:
- [x] eval-okay-tryeval
- [x] eval-okay-redefine-builtin

**Comment by jwiegley** [comment]
I think we should just move to `MonadThrow` and `MonadCatch` for this, with `MonadStack` being an embellishment on top of those for error reporting.
