### ISSUE TITLE
Automatic Arguments

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#111]
Nix supports passing arguments using `--arg` and `--argstr` like [this](https://github.com/ryantrinkle/nix/blob/f2273b11f5aec82fd4546aff6ff621aeb397f794/tests/lang/eval-okay-autoargs.flags).  We need ways to:
- [x] Parse them from the `.flags` file
- [x] Use them in the evaluator

This will fix eval-okay-autoargs

**Comment by jwiegley** [comment]
As well as this usage on the command-line:

```
[nix-shell:~/src/hnix]$ nix-instantiate --eval -E "{ a ? 1 }: a + 3" --arg a 2
5

[nix-shell:~/src/hnix]$ nix-instantiate --eval -E "{ a ? 1 }: a + 3"
<LAMBDA>
```

**Comment by jwiegley** [comment]
Just need to transform uses of `--arg a b` into `--arg a=b` for Nix, since `optparse-applicative` doesn't support odd argument parsing like this.
