### ISSUE TITLE
Search Path

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#112]
We need a way to alter the search path where nix looks for files in angle brackets, e.g. `<nixpkgs>`.  We need ways to:
- [x] Parse them from the `.flags` file
- [x] Use them in the evaluator

This will fix eval-okay-search-path

**Comment by jwiegley** [comment]
This would be implemented in `findEnvPath`, in `Exec.hs`.  Right now the code is:

``` haskell
    findEnvPath name = getEnvVar name >>= \case
        Nothing ->
            throwError $ "file '" ++ name
                ++ "' was not found in the Nix search path"
                ++ " (add it using $NIX_PATH or -I)"
        Just path -> makeAbsolutePath path
```

It just needs to be changed to lookup `NIX_PATH`, split the string apart, find `foo=bar` for the argument `foo` passed to `findEnvPath`, and then return the result of calling `makeAbsolutePath` on `bar`.

**Comment by jwiegley** [comment]
We'll also need to handle `-I` as a command-line option in `main/Main.hs`, and add a mapping of names to paths to the `Context`, which `findEnvPath` would consult first before looking up `NIX_PATH`.

**Comment by jwiegley** [comment]
I've adding processing of the `-I` flag, and the logic to normalize it down to either a single text field, or a pair of fields. All that needs to be done now is the right path surgery for each possible case, checking if the path exists, and calling `makeAbsolutePath` on the result.  See the notes and documentation in `findEnvPath` to get started.

**Comment by jwiegley** [comment]
@ryantrinkle We also need to implement `__nixPath`, which on my system reports:

```
[nix-shell:~/src/hnix]$ nix-instantiate --eval --expr __nixPath
[ { path = "/nix/var/nix/profiles/per-user/root/channels"; prefix = ""; }
  { path = "/nix/store/2yf43q8yqjmg66y2y55laixnf7666km2-nix-2.0/share/nix/corepkgs"; prefix = "nix"; } ]
```

The first entry comes from the `NIX_PATH`, but where does the second one come from?  It seems it was compiled into the Nix binary.

**Comment by jwiegley** [comment]
OK, almost everything is done except for this:

```
Current file being evaluated is: "data/nix/tests/lang/eval-okay-search-path.nix"
Importing file /Users/johnw/src/hnix/data/nix/tests/lang/dir4/a.nix
NApp
callFunc:NVBuiltin import
[p] = dir4
name = b.nix
cand = dir4/b.nix
path = /Users/johnw/src/hnix/data/nix/tests/lang/dir4/b.nix
exists = False
path' = /Users/johnw/src/hnix/data/nix/tests/lang/dir4/b.nix
exists = False
[p] = lang/dir1
cand = lang/dir1/b.nix
path = /Users/johnw/src/hnix/data/nix/tests/lang/lang/dir1/b.nix
exists = False
path' = /Users/johnw/src/hnix/data/nix/tests/lang/lang/dir1/b.nix
exists = False
```

As you can see at the end, we're duplicating `lang/lang` in the absolute path, which causes us not to find the file wanted by the test.  Also, I don't know why it's assuming that the `__nixPath` will have 6 elements in it, when it's only adding 3 more entries via the `.flags` file.

**Comment by jwiegley** [comment]
I think what this means is that when appending `foo/bar/baz` onto a NIX_PATH of `/nix/foo/bar`, it's intended to be `/nix/foo/bar/baz`?  I.e., you elide where the two overlap?
