### ISSUE TITLE
Regex support

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#113]
These two [Builtins](https://nixos.org/nix/manual/#ssec-builtins) can be added [here](https://github.com/jwiegley/hnix/blob/735c5ca15ab2beb09a51d7551d5e362bbbbc5793/Nix/Builtins.hs#L133):
- [x] builtins.split
- [x] builtins.match

This will fix:

- [x] eval-okay-regex-split
- [x] eval-okay-regex-match

**Comment by jwiegley** [comment]
The behavior of `match` is almost the same as pcre-light's `match`, but `split` will require some special code in `hnix`.

**Comment by mightybyte** [comment]
From a gitter conversation...

And https://nixos.org/nix/manual/#ssec-builtins specifically says these functions use "extended POSIX regular expression"

http://hackage.haskell.org/package/regex-tdfa-1.2.3/docs/Text-Regex-TDFA.html seems to suggest that there might be subtle corner cases:

> This regex-tdfa package implements, correctly, POSIX extended regular expressions. It is highly unlikely that the regex-posix package on your operating system is correct

So I'm going to look into using regex-tdfa for this.

**Comment by mightybyte** [comment]
PR #150 switches to regex-tdfa for match.

**Comment by mightybyte** [comment]
I'm working on `builtins.split`.

**Comment by mightybyte** [comment]
eval-okay-regex-split is now passing, so this can be closed.
