### ISSUE TITLE
builtins.listToAttrs

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#116]
This [Builtin](https://nixos.org/nix/manual/#ssec-builtins) should be added [here](https://github.com/jwiegley/hnix/blob/735c5ca15ab2beb09a51d7551d5e362bbbbc5793/Nix/Builtins.hs#L133).

Fixes eval-okay-listtoattrs

**Comment by jwiegley** [comment]
The builtin is implemented, but we'll need to implement `throw` to get the test working.
