### ISSUE TITLE
builtins.unsafeGetAttrPos

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#117]
This [Builtin](https://nixos.org/nix/manual/#ssec-builtins) should be added [here](https://github.com/jwiegley/hnix/blob/735c5ca15ab2beb09a51d7551d5e362bbbbc5793/Nix/Builtins.hs#L133).

Fixes eval-okay-getattrpos

**Comment by jwiegley** [comment]
This was quite an invasive change, but since nixpkgs relies on it for error reporting, it seemed needful.
