### ISSUE TITLE
Parsing: eval-okay-attrs5

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#127]
```
Exception: Parsing failed for file `data/nix/tests/lang/eval-okay-attrs5.nix`.
        ErrInfo {_errDoc = data/nix/tests/lang/eval-okay-attrs5.nix:9:3: error: expected: "in",
            inherited binding,
            variable binding
          or = x: y: x || y; 
          ^                  , _errDeltas = [Directed "data/nix/tests/lang/eval-okay-attrs5.nix" 8 2 102 2]}
        CallStack (from HasCallStack):
          error, called at tests/NixLanguageTests.hs:124:9 in main:NixLanguageTests
```

Fixes eval-okay-attrs5

**Comment by jwiegley** [comment]
I don't think we ever want to fix this. The part of the test that's failing is asserting "backwards compatibility", indicating that the ability to use reserved keywords like this for attributes is perhaps not something intended for the future.

Nor do I see how hnix could ever support it, since it requires the parser to understand the evaluation scope in order to see that "or" is a bound name by the time it parses that expression.

**Comment by ryantrinkle** [comment]
Wow, that is gross!  However, I think it might be *slightly* less gross than it appears.  For example:
```
nix-repl> let f = x: x; in f or 1
error: undefined variable 'or' at (string):1:18

nix-repl> let f = x: x; in f.y or 1
1

nix-repl> let f = x: x; in (f.y) or 1
error: undefined variable 'or' at (string):1:18
```
Based on some experimentation, it looks like `or` is interpreted as a variable reference anytime the form to its left is not - syntactically - an attribute lookup.  I *think* the syntactic classification doesn't actually depend on whether `or` is in scope.

**Comment by jwiegley** [comment]
@ryantrinkle OK, that's fair.

**Comment by ryantrinkle** [comment]
Still gross, though! :P

**Comment by jwiegley** [comment]
And still, this is only for backwards compatibility, so unless nixpkgs uses it, I suggest we defer implementing it.

**Comment by jwiegley** [comment]
Looks like this is used in `lib/attrsets.nix`.

**Comment by ryantrinkle** [comment]
Fixed by https://github.com/jwiegley/hnix/commit/a5069c620d1e107f11da6b235ba806848ff27c81 and https://github.com/jwiegley/hnix/commit/7a49e00c5d5afad6ecf03a5d5047c7bb20a4fcdc
