### ISSUE TITLE
Implement builtins.path

### ISSUE THREAD

**Issue by ryantrinkle** [haskell-nix/hnix#128]
This [Builtin](https://nixos.org/nix/manual/#ssec-builtins) should be added [here](https://github.com/jwiegley/hnix/blob/735c5ca15ab2beb09a51d7551d5e362bbbbc5793/Nix/Builtins.hs#L133).

This doesn't have a `.exp` file; I think that means it just needs to evaluate without error.

Fixes `eval-okay-path` (remove it from `newFailingTests` list).

**Comment by jwiegley** [comment]
This could be challenging, since I think these "enriched paths" are supposed to be interchangeable with other paths.

**Comment by xplat** [comment]
nix actually handles this by figuring out the store path and using that as a plain path object.  There are no actual 'enriched path objects' in nix libexpr.

**Comment by xplat** [comment]
Actually now that i  check more closely, builtins.path returns a string, not a path!

**Comment by domenkozar** [comment]
Right:

```
nix-repl> :t builtins.path { name = "patchelf"; path = ./patchelf; }
a string with context
```

**Comment by jglukasik** [comment]
I started looking into this today. Haven't made much progress, but I'm getting more familiar with the codebase. Will try again tomorrow.

**Comment by jwiegley** [comment]
Great! Once this is closed we’ll be able to turn on the full language tests for Travis!

**Comment by mightybyte** [comment]
@jglukasik Definitely ask for some help from someone on this tomorrow.  @shlevy will have all the knowledge you need on the nix side of things.  It would be great to get this one finished this weekend.

**Comment by jglukasik** [comment]
After some discussion with @mightybyte , we've realized this might be a bit too large of a first change for me. I'll let someone else tackle this.

**Comment by jwiegley** [comment]
I'm going to work on this on the plane tomorrow.

**Comment by shlevy** [comment]
@jwiegley This requires nar serialization, which @imalsogreg is working on

**Comment by jwiegley** [comment]
I realized that soon after looking into it, so I’m going to hold off and leave you guys to it.

**Comment by jwiegley** [comment]
@shlevy  since were not reimplementing the store, what are you think about binding to libstore through the FFI?

**Comment by ryantrinkle** [comment]
We could also shell out as I did for derivationStrict; it's dirty, but if it's easier it might be worth it since we should eventually try not to have a dependency at all.

**Comment by jwiegley** [comment]
I’m fine with shelling out right now, since it would let us move on to other problems.

**Comment by shlevy** [comment]
Eh, libnixstore isn't really stable at all and is not a nice interface at all. Not sure why we'd prefer that to implementing the daemon protocol.

**Comment by ryantrinkle** [comment]
@shlevy Do you think it makes sense to shell out in the immediate future to get this working, and then use the daemon protocol as the next step?

**Comment by shlevy** [comment]
If that gets us something useful, sure. First step of the required logic to do readonly mode properly (so no need to talk to the daemon) is up at https://github.com/haskell-nix/hnix-store/pull/7

**Comment by Anton-Latukha** [comment]
`layus` was implementing `path` in #755.
It for ported to the current code in #1032. Passes the basic test (`./data/nix/tests/lang//eval-okay-path.nix`).
