### ISSUE TITLE
builtins.genericClosure

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#144]
This is needed for `eval-okay-closure`.

**Comment by ryantrinkle** [comment]
Marking this as "good first issue".  Note: it has nothing to do with function closures - it's more like a repeated concatMap that keeps going until it stops finding new things.

See the C++ implementation here: https://github.com/NixOS/nix/blob/b828051659cf7cac21577982afd3f9314dc2e68c/src/libexpr/primops.cc#L341-L403

**Comment by hSloan** [comment]
I'm picking this up

**Comment by jwiegley** [comment]
@hSloan Great, Ishaq! And I'm happy to see you around here. :)
