### ISSUE TITLE
Priority of `NSelect` and `NConcat`

### ISSUE THREAD

**Issue by Ekleog** [haskell-nix/hnix#152]
While parsing `<nixpkgs/nixos/tests/radicale.nix>`, I came upon what I think is a bug in `hnix`.

Indeed, if I ask the parse result of `{ a = [1]; }.a or [2] ++ [3]`, `hnix` answers this:
```haskell
Fix (NSelect (Fix (NSet [NamedVar [StaticKey "a"] (Fix (NList [Fix (NConstant (NInt 1))]))])) [StaticKey "a"] (Just (Fix (NBinary NConcat (Fix (NList [Fix (NConstant (NInt 2))])) (Fix (NList [Fix (NConstant (NInt 3))]))))))
```
that is approximately
```haskell
NSelect
  (NSet ...)
  ["a"]
  (NConcat (NList [2]) (NList [3]))
```

Especially, the `NSelect` is placed top-level.

However, in `nix repl`, I get the following result:
```nix
nix-repl> { a = [1]; }.a or [2] ++ [3]
[ 1 3 ]
```

Which means `NConcat` should be placed top-level, and the tree should look like:
```haskell
NConcat
  (NSelect (NSet ...) [StaticKey "a"] (NList [2]))
  (NList [3])
```

Does what I'm saying make sense?

**Comment by ryantrinkle** [comment]
Yep! Looks like a bug. Perhaps binary operators shouldn't be in nixTerm?

**Comment by Ericson2314** [comment]
`or` has very odd precedence, unlike infix operators in Haskell or the others in Nix. I think it binds as tightly as function application, perhaps both `or`s are parsed the same.

**Comment by Profpatsch** [comment]
`or` binds tighter than function application.

```
nix-repl> let f = x: x+1; in { a = f 23; }.a or (f 42)
24

nix-repl> let f = x: x+1; in { a = f 23; }.a or f 42
error: attempt to call something which is not a function but an integer, at (string):1:20
```

**Comment by ryantrinkle** [comment]
@Ericson2314 Yep, as @Profpatsch mentioned, it's tighter than function application.  I think it's best thought of as *part of* the the field lookup syntax, which is how the parser currently does it.

**Comment by Ekleog** [comment]
(also see https://nixos.org/nix/manual/#table-operators)

**Comment by Profpatsch** [comment]
@ryantrinkle Sorry, I deleted my comment because the examples didn’t work out in the end. But I’m fairly certain `or` binds more strongly than function application, because I’ve stumbled over it in this function:

```nix
let
  matchDef = def: matcher: v:
    let case = builtins.head (builtins.attrNames v);
    in (matcher.${case} or (def case)) v.${case};
in null
```

It doesn’t work if I remove the parens around `(def case)`.

**Comment by jwiegley** [comment]
This got fixed by the switch to `megaparsec`, as a result of other fixes I did during the migration.

**Comment by Ekleog** [comment]
Great, thanks!

**Comment by jwiegley** [comment]
@Profpatsch According to the precedence table, `a.b [or c]` binds tighter than anything else.
