### ISSUE TITLE
Implement all of the builtins actually used by nixpkgs

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#157]
It's possible this may include some features not exercised by the language tests.

The symbolic evaluator should be good example of writing a custom `grep`-style tool for doing pointed queries like this, since it can take `with` and `let` bindings into account.

From @mightybyte: Comparing this with what we have in `Builtins.hs`, we are missing at least these functions:

- [ ] currentTime
- [ ] div
- [ ] fetchurl
- [ ] filterSource
- [ ] genericClosure
- [ ] hasContext
- [ ] langVersion
- [ ] max
- [ ] min
- [ ] nixPath
- [x] nixVersion
- [ ] storeDir
- [ ] storePath
- [ ] toFile
- [ ] trace

**Comment by mightybyte** [comment]
Here are all the unique things matching `builtins.\w+` that I found in nixpkgs.  This doesn't take `with` and `let` bindings into account, but should be a good start.

builtins.add
builtins.all
builtins.any
builtins.attrNames
builtins.attrValues
builtins.baseNameOf
builtins.catAttrs
builtins.compareVersions
builtins.concatLists
builtins.concatStringsSep
builtins.currentSystem
builtins.currentTime
builtins.deepSeq
builtins.div
builtins.elem
builtins.elemAt
builtins.fetchurl
builtins.filter
builtins.filterSource
builtins.foldl'
builtins.fromJSON
builtins.functionArgs
builtins.genList
builtins.genericClosure
builtins.getAttr
builtins.getEnv
builtins.hasAttr
builtins.hasContext
builtins.hashString
builtins.head
builtins.intersectAttrs
builtins.isAttrs
builtins.isBool
builtins.isFunction
builtins.isInt
builtins.isList
builtins.isNull
builtins.isString
builtins.langVersion
builtins.length
builtins.lessThan
builtins.listToAttrs
builtins.map
builtins.match
builtins.max
builtins.min
builtins.nixPath
builtins.nixVersion
builtins.parseDrvName
builtins.partition
builtins.pathExists
builtins.readDir
builtins.readFile
builtins.removeAttrs
builtins.replaceStrings
builtins.seq
builtins.sort
builtins.split
builtins.splitVersion
builtins.storeDir
builtins.storePath
builtins.stringLength
builtins.sub
builtins.substring
builtins.tail
builtins.throw
builtins.toFile
builtins.toJSON
builtins.toPath
builtins.toString
builtins.toXML
builtins.trace
builtins.tryEval
builtins.typeOf
builtins.unsafeDiscardStringContext
builtins.unsafeGetAttrPos

**Comment by mightybyte** [comment]
Comparing this with what we have in `Builtins.hs`, we are missing at least these functions

currentTime
div
fetchurl
filterSource
genericClosure
hasContext
langVersion
max
min
nixPath
nixVersion
storeDir
storePath
toFile
trace

**Comment by jwiegley** [comment]
Thanks @mightybyte! I've converted your last comment into a work list.

**Comment by jwiegley** [comment]
I wonder how `nixPath` differs from `__nixPath`...

**Comment by jwiegley** [comment]
These are all broken out into separate issues now.
