### ISSUE TITLE
Scoping is wrong in rec sets with path accessors

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#178]
If you evaluate `nixpkgs` with this command:

```
./dist/build/hnix/hnix --eval --expr "import $HOME/src/nix/nixpkgs {}"
```

It dies for me on line 209 of `lib/systems/parse.nix`, complaining that for the accessor `types.cpuType.check`, that `types` does not contain `cpuType`.

The problem here is that hnix is resolving `types` to the field brought in by `lib/types.nix` (at the top of the file), and not to the `types` field which is defined as part of the enclosing rec set, but always by using a dotted path, such as:

```
  types.cpuType = enum (attrValues cpuTypes);
```

**Comment by domenkozar** [comment]
This was fixed.
