### ISSUE TITLE
Expose lexer + keep token sizes

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell-nix/hnix#18]
Text editors could benefit from the hnix lexer but it seems only the parser is exposed which is much less useful for things like syntax-highlighting in classical editing scenario. It'd be great if the lexer was exposed and if it carried token sizes/locations.

**Comment by jwiegley** [comment]
@Fuuzetsu Excellent idea, let's do that.

**Comment by expipiplus1** [comment]
This has been brought up in #35 as a possible improvement to that PR.

**Comment by jwiegley** [comment]
@Fuuzetsu The parse tree now carries full location information (start/stop ranges) for every parsed entity. I'm not sure how to get you the underlying "token stream" since we're using megaparsec and not doing a two-phase parse.

**Comment by Fuuzetsu** [comment]
Maybe it's enough as is now.  No time to check but I'll open new tickets if I try it and need more.
