### ISSUE TITLE
Add a --trace option for --eval to reproduce the "relevant expression context"

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#183]
If, during evaluation, we record the expression trees involved, and "color" them as we go, then at the point of reaching `throwError` we could dump the minimal expression tree relevant to the error:

  - Delete unreferenced set members
  - Delete unreferenced function arguments (if taking a parameter set)
  - Delete unused default arguments
  - Replace unevaluated thunks with nulls

This would make it easier to turn errors into test cases.

**Comment by jwiegley** [comment]
This is actually done now! I'm going to have to write a blog post tonight on how powerful recursion schemes can be. I was able to add this functionality without changing a single line in the original data types or evaluators.

**Comment by jwiegley** [comment]
@ryantrinkle The option is `--trace`, which for the given input file:

```
let x = { z = import ./eighty.nix + 20; w = 123; };
    y = "Hello";
    z = "Goodbye";
in assert 1 == 1; if x.z == 100 then y else 3
```

Produces this output:

```
Expression tree before winnowing:
--------
let
  x = {
    z = import ./eighty.nix + 20;
    w = 123;
  };
  y = "Hello";
  z = "Goodbye";
in assert 1 == 1;
if x.z == 100 then y else 3
--------
Expression tree after winnowing:
--------
let
  x = {
    z = 80 + 20;
    w = null;
  };
  y = "Hello";
in y
--------
"Hello"
```

This is actually working well enough that it produces a file which reproduces the `<<loop>>` I'm encountering in `nixpkgs` right now, in less than 10k lines.  It still contains imports when those imports are the result of evaluation (i.e., the tracer can't see the import directly).

**Comment by jwiegley** [comment]
I need to use an evaluator here that does "no effect reduction", to further simplify the resulting expression tree and discover more importing opportunities. Right now the following fails to trigger a static load:

```
let callLibs = file: import file { lib = self; };
    trivial = callLibs ./trivial.nix;
in trivial
```

Also, we should be able to reduce all statically computable subexpressions. This will mean flagging builtins to know which cause external effects and which are pure.

**Comment by ryantrinkle** [comment]
This is insanely awesome.  Both the functionality and the fact that it was so clean to add.

**Comment by domenkozar** [comment]
:+1:  :+1:  :+1:

**Comment by gilligan** [comment]
😻

**Comment by jwiegley** [comment]
The code for this approach is here: https://github.com/jwiegley/hnix/blob/master/src/Nix/Trace.hs. Note that the only function doing real work is `pruneTree`, which decides what it means when an expression node has unreferenced parts. This code is called from here: https://github.com/jwiegley/hnix/blob/master/src/Nix/Entry.hs#L74

**Comment by jwiegley** [comment]
Blog article describing this process is up: http://newartisans.com/2018/04/win-for-recursion-schemes/

**Comment by jwiegley** [comment]
The pure reduction evaluator is now working and is part of `--trace`.  See `Reduce.hs` for more details.
