### ISSUE TITLE
Drop the FromNix type class

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#201]
`FromNix` is currently useful for two things: converting an incoming value action into a list or a hashmap of `Text` values. Using `FromValue`, such a recursion requires two steps. This is used by `ToBuiltin` to make it easier to turn native functions over these types into Nix builtins.

However, this type class is dangerous when used incorrectly, with no indication of the danger at any point in time. Therefore, I think these two specific conversions should always be done manually, even if at the cost of convenience in some cases.

**Comment by Anton-Latukha** [comment]
Was done by `mightybyte` in 5dd3e2d7cebac11d2b9777cae8c87777a3808b41.
