### ISSUE TITLE
Hnix on hackage?

### ISSUE THREAD

**Issue by adnelson** [haskell-nix/hnix#21]
Is there a reason hnix isn't on Hackage? I just switched it in as a dependency for a project that I have but realized that my package won't be able to be built on hackage because hnix isn't there.

**Comment by jwiegley** [comment]
No reason, actually. I'll upload it now.

**Comment by jwiegley** [comment]
http://hackage.haskell.org/package/hnix

**Comment by adnelson** [comment]
Yay!
