### ISSUE TITLE
replaceStrings should preserve string context information

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#210]
That is, it should propagate the DLists, not drop them as it's now doing.

Permalink:
https://github.com/haskell-nix/hnix/blob/1e2bd9eb2f366da7d98f2aee876bc97f6da37707/src/Nix/Builtins.hs#L507-L535

**Comment by mightybyte** [comment]
I believe this is addressed by #405.

Result:
https://github.com/haskell-nix/hnix/blob/281644a3b2a2b1a488fde771748d88102ab6eb6b/src/Nix/Builtins.hs#L722-L755

**Comment by Anton-Latukha** [comment]
Do the function is long & complex: https://github.com/haskell-nix/hnix/pull/405/files#r240045660

Lets untangle this thread *(makes updates to the messages in the thread)*.

Current code:
https://github.com/haskell-nix/hnix/blob/eb709ccb4a35d4725549914aebfcecc998959750/src/Nix/Builtins.hs#L926-L976

**Comment by Anton-Latukha** [comment]
So:
```
    -- `ns*` goes for NixString here
    fromValue ts >>= \(ns :: NixString) ->
      ...
        go orig result ctx =
          -- and it returns (ctx) OR (ctx <> newCtx)
           ...
      toValue
        $ go (stringIgnoreContext ns) mempty
        $ NixString.getContext ns
```

So I believe that this is indeed closed.

Tail call func `toValue` indeed saves the context, drops the context, and loads new context in place.
