### ISSUE TITLE
The Generic1 instance for NKeyName is incorrect

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#225]

**Comment by expipiplus1** [comment]
Is it possible to at least remove the instance, it's quite confusing to come across it like this!

**Comment by expipiplus1** [comment]
This may be useful for anyone wanting to use `NKeyName` somewhat generically (Although these don't have `Generic1` instances):

```
Antiquoted (NString r) r = Antiquoted (NString r) (Identity r)
                         = Biff Antiquoted NString Identity r r
                         = Join (Biff Antiquoted NString Identity) r
```

**Comment by jwiegley** [comment]
If it still builds and passes tests without it, can you please submit a PR? Seems like a simple enough thing to merge.

**Comment by expipiplus1** [comment]
Done, thanks

**Comment by jwiegley** [comment]
Thank you!
