### ISSUE TITLE
Variadic functions don't parse

### ISSUE THREAD

**Issue by adnelson** [haskell-nix/hnix#23]
Hnix doesn't currently parse variadic (`...`) arguments:

```
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
[1 of 3] Compiling Nix.Types        ( Nix/Types.hs, interpreted )
[2 of 3] Compiling Nix.Parser.Library ( Nix/Parser/Library.hs, interpreted )
[3 of 3] Compiling Nix.Parser       ( Nix/Parser.hs, interpreted )
Ok, modules loaded: Nix.Parser, Nix.Parser.Library, Nix.Types.
*Nix.Parser> parseNixString "{x, ...}: x"
Failure <string>:1:3: error: expected: "=",
    ., letter or digit
{x, ...}: x<EOF> 
  ^              
*Nix.Parser> 
```

Also this isn't represented in the AST. This is the way that `simple-nix` encapsulates this:

``` haskell
data FuncArgs
  = Arg Name
  | Kwargs (HashMap Name (Maybe NixExpr)) Bool (Maybe Name)
  deriving (Show, Eq)
```

Where the boolean indicates if it's variadic, and the `Maybe Name` indicates whether it has an `@`. I think it might be sufficient to modify the `FormalParamSet` type to add a flag indicating if it's variadic or not, and add machinery to parse that.

**Comment by jwiegley** [comment]
Sounds good @adnelson.
