### ISSUE TITLE
Implement builtins.fetchurl

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#232]

**Comment by wavewave** [comment]
i am working on this issue.

**Comment by wavewave** [comment]
#258 implements this.

**Comment by wavewave** [comment]
ok. #258 does not implement the function truly.

**Comment by wavewave** [comment]
new partial implementation #265.  getURL is introduced and does actual fetching. Since getting correct hash and /nix/store path is not implemented, this task cannot be completed yet.
