### ISSUE TITLE
Implement builtins.toFile

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#241]

**Comment by kerbyferris** [comment]
I can give this one a try.

**Comment by kerbyferris** [comment]
Nvm, best to try a different one. Progress made: Probably needs a new monad effect, and likely involves creating a temp file requiring MonadMask. Currently using MonadCatch

**Comment by hSloan** [comment]
I'm picking this one up.

**Comment by sorki** [comment]
Looks like this one can be closed ^^.
