### ISSUE TITLE
Support all of the primops

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#243]
https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L2084

- [x] __add
- [ ] __addErrorContext
- [x] __all
- [x] __any
- [x] __attrNames
- [x] __attrValues
- [x] __catAttrs
- [x] __compareVersions
- [x] __concatLists
- [x] __concatStringsSep
- [x] __currentSystem
- [x] __currentTime
- [x] __deepSeq
- [x] __div
- [x] __elem
- [x] __elemAt
- [ ] __exec
- [x] __fetchurl
- [x] __filter
- [x] __filterSource
- [ ] __findFile
- [x] __foldl'
- [x] __fromJSON
- [x] __functionArgs
- [x] __genList
- [x] __genericClosure
- [x] __getAttr
- [x] __getEnv
- [x] __hasAttr
- [x] __hasContext
- [x] __hashString
- [x] __head
- [ ] __importNative
- [x] __intersectAttrs
- [x] __isAttrs
- [x] __isBool
- [x] __isFloat
- [x] __isFunction
- [x] __isInt
- [x] __isList
- [x] __isString
- [x] __langVersion
- [x] __length
- [x] __lessThan
- [x] __listToAttrs
- [x] __match
- [ ] __mul
- [x] __nixVersion
- [x] __parseDrvName
- [x] __partition
- [ ] __path
- [x] __pathExists
- [x] __readDir
- [x] __readFile
- [x] __replaceStrings
- [x] __seq
- [x] __sort
- [x] __split
- [x] __splitVersion
- [x] __storeDir
- [x] __storePath
- [x] __stringLength
- [x] __sub
- [x] __substring
- [x] __tail
- [x] __toFile
- [x] __toJSON
- [x] __toPath
- [x] __toXML
- [x] __trace
- [x] __tryEval
- [x] __typeOf
- [ ] __unsafeDiscardOutputDependency
- [x] __unsafeDiscardStringContext
- [x] __unsafeGetAttrPos
- [ ] __valueSize
- [ ] placeholder

**Comment by jwiegley** [comment]
Many of these just seem to be alternative global names for things that live in `builtins`.

**Comment by shlevy** [comment]
*All* of them are alternative global names for things that live in builtins :smile: https://github.com/NixOS/nix/blob/8e7d77d4944d7903f64dc8d61a43f81221cd4aea/src/libexpr/eval.cc#L416-L419 (`baseEnv.values[0]` is `builtins`)

**Comment by jwiegley** [comment]
I've also checked the ones that will be implemented once other issues are resolved.

**Comment by jwiegley** [comment]
Added as separate issues.
