### ISSUE TITLE
NAR and NAR export serialization code

### ISSUE THREAD

**Issue by adnelson** [haskell-nix/hnix#283]
Maybe related to #128, maybe not, but I thought I'd ask:

I have code for serializing and deserializing NARs and "exported" NARs (including metadata) that I reverse engineered from the C++ implementation a while ago. It currently lives here: https://github.com/adnelson/nix-binary-cache/blob/master/src/Nix/Nar/Serialization.hs 
I'm not sure if this already being worked on, or where it would fit into the `hnix` code if we wanted it here, but I'd be happy to merge them into this one.

**Comment by mightybyte** [comment]
Pinging @imalsogreg

**Comment by adnelson** [comment]
Maybe this would actually be better suited to the `hnix-store` repo... 🤔

**Comment by adnelson** [comment]
Posted there, closing here :)
