### ISSUE TITLE
Implement a Lift instance for NExpr in a way that works with GHC 8.0

### ISSUE THREAD

**Issue by mightybyte** [haskell-nix/hnix#284]
The current implementation uses `Type.Reflection` which does not work with GHC 8.0:

https://github.com/haskell-nix/hnix/blob/minimize-deps/src/Nix/Expr/Types.hs#L154

Building with GHC 8.0 is blocking work on a web-based REPL for nix expressions, which has a lot of great potential.  If anyone can implement this instance in an 8.0-compatible way, that would be a big help.

The Lift type class is defined here:

http://hackage.haskell.org/package/template-haskell-2.13.0.0/docs/Language-Haskell-TH-Syntax.html#t:Lift

**Comment by sboosali** [comment]
@mightybyte if you can explain to me what's needed:

https://github.com/haskell-nix/hnix/blob/master/src/Nix/Expr/Types.hs#L159 (the other link in this thread seems to be on a dead branch)

I can try to do this (as a first issue on this project). That is, does Reflection only work with ghc8+? Or does the usage in this project specifically not work in ghc8.0?

**Comment by jwiegley** [comment]
Actually, I don't think this is needed anymore. I resolved the matter by just not using Type.Reflection with 8.0:

```
#if MIN_VERSION_base(4, 10, 0)
instance Lift (Fix NExprF) where
    lift = dataToExpQ $ \b ->
        case Reflection.typeOf b `eqTypeRep` Reflection.typeRep @Text of
            Just HRefl -> Just [| pack $(liftString $ unpack b) |]
            Nothing -> Nothing
#else
instance Lift (Fix NExprF) where
    lift = dataToExpQ $ \b -> case cast b of
        Just t -> Just [| pack $(liftString $ unpack t) |]
        Nothing -> Nothing
#endif
```
