### ISSUE TITLE
Put the evaluated object into scope when using --repl --eval

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#292]
Pinging @hSloan, who asked for this feature.  It should just be a matter of checking whether the evaluated object is an attrset, and if so, wrapping the call that enters the repl in a call to `pushScope`.

**Comment by hSloan** [comment]
Thanks for reminding me, I'm picking this one up.

**Comment by domenkozar** [comment]
@hSloan are you working on this? I'm working on extending repl with scope state and type command support.

**Comment by mightybyte** [comment]
@domenkozar He was working on it yesterday.

**Comment by domenkozar** [comment]
I made a tiny steps towards this in https://github.com/haskell-nix/hnix/pull/409, but it's not ready yet.
