### ISSUE TITLE
Evaluating 'system' of nixpkgs fails with assertion

### ISSUE THREAD

**Issue by infinisil** [haskell-nix/hnix#323]
Just running

```
hnix --eval -E '(import <nixpkgs> {}).system'
```
gives this error:
```
hnix: /home/infinisil/cfg/external/nixpkgs/lib/systems/parse.nix:252:5:
    |
252 |     assert types.parsedPlatform.check components;
    |     ^
Assertion failed: false
```

- hnix: 0.5.1 from
- nixpkgs: be5e8faafc69195ef47e9cf6b92806cf427656e1

**Comment by matthewbauer** [comment]
I'm debugging this now...

It appears that Hnix doesn't handle equality with functions correctly:

```
let
  f = { a = b: false; };
in

assert f == f;

derivation {
  name = "success";
  builder = "./asd";
  system = "x86_64-linux";
}
```

Works in Nix, but fails in Hnix

**Comment by Ericson2314** [comment]
Hmm I wrote that nixpkgs code, and I don't want it to compare functions like that regardless of the implementation!

**Comment by jwiegley** [comment]
Well, that's interesting. And I can see why, since what `==` sees has already been reduced to a Haskell lambda by that time; we can't "compare expression bodies" anymore by then.

**Comment by ryantrinkle** [comment]
Thankfully, what Nix does seems to not be so bad, here!

```nix
nix-repl> let f = x: x; in f == f 
false
```

From this, and a bit more vague poking around, it appears that functions always compare as unequal.

**Comment by matthewbauer** [comment]
Does it just ignore functions in attr sets then? That would actually be pretty easy to fix in hnix i think.

On the other hand, since it is not very common, it might make sense to just remove this in Nixpkgs and put the assertions somewhere else. I guess that’s kind of cheating though.

**Comment by matthewbauer** [comment]
Yeah so it looks like:

```
$ nix eval '(let f = x: x; in f == f)'
false
$ nix eval '(let a = {f = x: x;}; in a == a)'
true
```

**Comment by matthewbauer** [comment]
Also this:

```
$ nix eval '(let a = [(x: x)]; in a == a)'
true
```

**Comment by ryantrinkle** [comment]
Oh, gross.  Good find, though!
