### ISSUE TITLE
SourcePos leaks into the inherit shorthand

### ISSUE THREAD

**Issue by Profpatsch** [haskell-nix/hnix#326]
`inherit :: [NKeyName e] -> SourcePos -> Binding e`
where before it was just `inherit :: [NKeyName e] -> Binding e`.
Same with `inheritFrom`.

As the shorthands module is for generating nix expression, not defaulting to `nullPos` doesn’t really make sense (since the user is not a parser and has no access to a filename or source position).

**Comment by jwiegley** [comment]
Agreed, @Profpatsch.
