### ISSUE TITLE
Reporting of attribute errors from `--find` is off

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#335]
When `--find` shows an error while evaluating an attribute, the attribute in which the error occurs is not the attribute that is reported.

Pinging @imalsogreg.

**Comment by domenkozar** [comment]
I can't seem to reproduce this on master:

```
hnix --eval -E '{ a = 3; b = throw "oh no!"; }' --find
Exception forcing b: oh no!
a
b
```

**Comment by jwiegley** [comment]
@domenkozar Oh, I forgot that I fixed this. The actual problem is that if an error had occurring during forcing a thunk, the thunk was left "open", so that if a later attribute tried to force the same thunk, it would erroneously raise a `<<loop>>` error.
