### ISSUE TITLE
Something's not right in mapAttrs

### ISSUE THREAD

**Issue by pikajude** [haskell-nix/hnix#353]
In the hnix repl:

```
hnix> (builtins.mapAttrs (n: v: v 3) { foo = x: x > 4; }).foo
<closure>
```

In nix:

```
nix-repl> (lib.mapAttrs (n: v: v 3) { foo = x: x > 4; }).foo
false
```

**Comment by pikajude** [comment]
Looks like the mapping function is meant to take both the key and value as arguments, but hnix's version only accepts the value.

**Comment by Profpatsch** [comment]
I recommend running the test suite in https://github.com/NixOS/nixpkgs/blob/master/lib/tests/misc.nix to catch this and similar errors. Is there a test suite for builtins already?

**Comment by domenkozar** [comment]
@Profpatsch how to run that via `--eval -E '...'`? :)

**Comment by Profpatsch** [comment]
With nix it’s:

```
$ nix-instantiate --strict --eval lib/tests/misc.nix
[ ]
```

It should return an empty list when the tests are successful.

**Comment by domenkozar** [comment]
Thanks - https://github.com/haskell-nix/hnix/issues/355

**Comment by jwiegley** [comment]
Let's add this to the tests that we run then!

**Comment by domenkozar** [comment]
fixed

**Comment by pikajude** [comment]
Fixed by https://github.com/haskell-nix/hnix/pull/356
