### ISSUE TITLE
Incorrect precedence when parsing "name or import ..."

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#359]
The following code:

```
  builtins.bitAnd
    or import ./zip-int-bits.nix
      (a: b: if a==1 && b==1 then 1 else 0)
```

is being parsed incorrectly as:

```
(builtins.bitAnd or import) ./zip-int-bits.nix (a:
  b:
    if a == 1 && b == 1
      then 1
      else 0)
```

When it should be:

```
builtins.bitAnd or (import ./zip-int-bits.nix (a:
  b:
    if a == 1 && b == 1
      then 1
      else 0))
```

**Comment by jwiegley** [comment]
@domenkozar This is blocking me on getting further with your problem, but should be fairly easy to remedy this week.

**Comment by jwiegley** [comment]
My assessment is incorrect. It should be working at the precedence it's parsing as now.

**Comment by jwiegley** [comment]
@shlevy It looks like `import` is processed as a keyword, rather than just another builtin function?

**Comment by jwiegley** [comment]
Should `foo.bar or baz 1` be intepreted as `(foo.bar or baz) 1` or `foo.bar or (baz 1)`? The precedence rules seems to suggest the former.

**Comment by jwiegley** [comment]
https://nixos.org/nix/manual/#table-operators suggests that `or` binds the most tightly, along with its associated selector.

**Comment by jwiegley** [comment]
Ah, we were right and nixpkgs was the problem: https://github.com/NixOS/nixpkgs-channels/commit/608730af4404f40586ba1e764fbc8576451ec513

**Comment by Profpatsch** [comment]
Haha, my bad :confounded:
