### ISSUE TITLE
Implement derivationStrict without nix-instantiate

### ISSUE THREAD

**Issue by shlevy** [haskell-nix/hnix#364]
Once we have string context and hnix-store integration, we can implement derivationStrict properly

**Comment by mightybyte** [comment]
I've been mucking around with this in my free time, but it's going really slowly.  @shlevy I was thinking it would be really nice to get your help on it.  Perhaps we could find a time to pair?

**Comment by shlevy** [comment]
Sure! Until we have proper support for string context and adding files to the store we'll be limited, but we can definitely make some progress.

**Comment by mightybyte** [comment]
For the record, here's the reference implementation that we have to match:

https://github.com/NixOS/nix/blob/master/src/libexpr/primops.cc#L523

**Comment by bqv** [comment]
ref #554
