### ISSUE TITLE
Parser sometimes drops parentheses

### ISSUE THREAD

**Issue by cransom** [haskell-nix/hnix#370]
I had been running some of my code through hnix as a pretty printer and noticed some errors afterwords:
```
0ogre:~% echo "(import ./example.nix).wheredidmyparensgo" | nix run -f channel:nixos-unstable haskellPackages.hnix -c hnix --parse -
import ./example.nix.wheredidmyparensgo
```
The statements aren't equivalent.

**Comment by Profpatsch** [comment]
This might have been fixed by https://github.com/haskell-nix/hnix/pull/332

**Comment by cransom** [comment]
It sure has. thanks!
