### ISSUE TITLE
Profiling tools

### ISSUE THREAD

**Issue by mightybyte** [haskell-nix/hnix#375]

**Comment by domenkozar** [comment]
Generating flamegraphs would be really nice. If we pick the same syntax as `ghc -pj`, we can also use already existing infrastructure to generate flamegraphs using https://github.com/Fuuzetsu/ghc-prof-aeson-flamegraph#readme

**Comment by Anton-Latukha** [comment]
Not enough information.

I already profiled the codebase as I can. I believe the Thunk implementation built on Ref-tf is the culprit of 1-threadedness & lazy suspension of thunks.

And debugger must be done, even for internal purposes, before thinking on putting any effort into profiler tooling.
