### ISSUE TITLE
Use Either instead of Result

### ISSUE THREAD

**Issue by langston-barrett** [haskell-nix/hnix#40]
Is there any reason in particular to define

``` haskell
data Result a :: * -> *
```

with constructors

``` haskell
Success a    
Failure Doc  
```

Rather than use `Either Doc a`?

**Comment by jwiegley** [comment]
I wonder if there was in the past, but it doesn't sound like there should be one.

**Comment by jwiegley** [comment]
It's there to support Parsec, since this is the value Trifecta returns.
