### ISSUE TITLE
Remove use of hpack

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#411]
The project has stabilized enough that `hpack` is no longer offering much benefit. We should take the `hnix.cabal` that we have now, and drop use of `hpack`.

This issue could also be titled "Early Christmas for @mightybyte".

**Comment by domenkozar** [comment]
With [Common stanzas](https://www.haskell.org/cabal/users-guide/developing-packages.html#common-stanzas) it should be almost identical in Cabal, minus automatic export-modules handling.
