### ISSUE TITLE
Ship nix/fetchurl.nix with hnix

### ISSUE THREAD

**Issue by domenkozar** [haskell-nix/hnix#419]
This gets us closer to simple usage :)

**Comment by jwiegley** [comment]
That file is in the tarball uploaded to Hackage:

    data/nix/corepkgs/fetchurl.nix

Do you want it made available in another way?

**Comment by domenkozar** [comment]
We could make it available on search path by default to avoid passing `-I nix=$PWD/data/nix/corepkgs`.

**Comment by jwiegley** [comment]
But how to know where it will end up being installed?

**Comment by ryantrinkle** [comment]
We could also embed it with TH. That is a bit easier to wrangle sometimes.
