### ISSUE TITLE
Dedup 32-bit hashing logic with code in hnix-store

### ISSUE THREAD

**Issue by mightybyte** [haskell-nix/hnix#425]
See also https://github.com/haskell-nix/hnix/pull/405/files/95d4b9406d80d9f9e86ce0125a0025d990ab8448#r240045800

cc @imalsogreg

**Comment by domenkozar** [comment]
Release hnix-store-core to hackage and depend on it? :)

**Comment by Ericson2314** [comment]
Where does hnix-store-core have a unix dep if the effects are abstracted? https://github.com/haskell-nix/hnix-store/blob/master/hnix-store-core/hnix-store-core.cabal#L44 Otherwise, sounds good to me!

**Comment by Anton-Latukha** [comment]
`hnix-store-core` was released.

The hashing logic was deduped.

Now there is no hashing logic in HNix that was referenced in the report.
