### ISSUE TITLE
Error traces are no longer useful since switching to Megaparsec 7

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#428]
All that I see now with `-v3` is:

```
offset=5:
While evaluating:
```

This should be reporting the file, line number, and the source (with 3 lines of context), as it did under Megaparsec 6.

**Comment by domenkozar** [comment]
cc @vaibhavsagar

**Comment by vaibhavsagar** [comment]
I suspect this is happening because of https://github.com/haskell-nix/hnix/pull/380/files#diff-fcbeb056e81a1275c04efb8c107238eeR70, as IIRC the new Megaparsec doesn't provide line and column numbers separately and instead just provides an offset into the input stream, so if we want the old behaviour back we'd need to 

1. Split the file by newlines
2. Find the line and column numbers corresponding to the offset we've been provided with.
3. Display the error with context accordingly.

**Comment by jwiegley** [comment]
Since it only happens at error reporting time, that seems like a reasonable approach.

**Comment by jwiegley** [comment]
It looks like the contextual error printing was removed from megaparsec, and replaced with `offset=N:`.

**Comment by jwiegley** [comment]
I've made progress on this with guidance from @mrkkrp here: https://github.com/mrkkrp/megaparsec/issues/338

**Comment by jwiegley** [comment]
Looks like using megaparsec for error reporting is a no go. They've changed too much to suit the particular needs of error-reporting-while-parsing, and it's broken the ability to easily report an error location after the fact.

This will need some new code to display lines within files, but it should be a fun exercise, entirely pure code, and only a few hours of work.

**Comment by mightybyte** [comment]
@jwiegley Since we know that performance is currently a problem for us, would it make sense to do the parsing with a faster parser that doesn't do error reporting, and then re-parse for better errors only when we've encountered an error?

**Comment by jwiegley** [comment]
@mightybyte Maintain two parsers? Until speed is critical, I'd rather not. This is by no means a trivial parser.

**Comment by xaverdh** [comment]
In principle this could be done using the [parsers](http://hackage.haskell.org/package/parsers) library, writing the parser polymorphic in the framework.

**Comment by jwiegley** [comment]
We were using `parsers` before `megaparsec`, actually. Wasn't worth the trouble to maintain it.

**Comment by jwiegley** [comment]
We're now reporting source context lines in our own way.
