### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Profpatsch** [haskell-nix/hnix#431]
hnix is currently broken on nixpkgs, because everything has updated to megaparsec 7 in the meantime. A new release would be great.

**Comment by jwiegley** [comment]
Once we restore proper error messages, it will be released. I've working on it over the past few days; getting close.

**Comment by domenkozar** [comment]
See #428

**Comment by jwiegley** [comment]
Released 0.6.0 today.

**Comment by domenkozar** [comment]
Now we need hnix-store-core release as hnix depends on it /cc @shlevy
