### ISSUE TITLE
Add test to verify string context behavior of builtins.split

### ISSUE THREAD

**Issue by mightybyte** [haskell-nix/hnix#435]

**Comment by hSloan** [comment]
I'll pick this one up

**Comment by layus** [comment]
This is specifically about string _context_ behavior. When splitting a string with a context, nix drops the context. We should ensure that we do the same as nix, possibly improving the status quo with a warning about discarding some context.

See  13fc5bcd6d4bddced6fe430398d4f3da005644fa for existing tests.

**Comment by Anton-Latukha** [comment]
Tests were provided.
