### ISSUE TITLE
Replace hnix's `StorePath` with hnix-store's `Path`

### ISSUE THREAD

**Issue by mightybyte** [haskell-nix/hnix#472]
The hnix-store work is probably still too much in flux (as of March 2019), but this will probably be something we want to do eventually.

**Comment by sorki** [comment]
Assigning my self to this and the rest of the `hacky*` issues.

**Comment by Anton-Latukha** [comment]
`hacky*` are mainly relate around `NixString` type, `StorePath` may be also.

I've opened a largely unanswered question-statement. Proper is to populate `NAtom` with all atomic Nix types that are atomic in the Nix design ("Can NixString be the NAtom?" #534).

Also probably related to the `hacky*` implementations is the "convert nix file to haskell json object" #539.

**Comment by sorki** [comment]
Interesting, I've tried to eval `release-combined.nix` and it looks pretty good except that `drv` paths are different compared to Nix - mostly caused by missing `inputSrcs` and `inputDrvs` from the derivation so I would like to tackle that now and reach parity with Nix.

**Comment by layus** [comment]
A discussion about this was raised in #554: https://github.com/haskell-nix/hnix/pull/554/files#r538011509 && https://github.com/haskell-nix/hnix/pull/554/files#r427298390
