### ISSUE TITLE
A new release

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#524]
I would love to see a new `hnix` release, mostly because of the current bounds on `prettyprinter`:

`dhall` needs `prettyprinter > 1.5` to fix some formatting issues (https://github.com/dhall-lang/dhall-haskell/issues/1400 and https://github.com/dhall-lang/dhall-haskell/pull/1422) but since it also relies on `hnix` via `dhall-nix`, it's difficult to build `dhall` with the new `prettyprinter` versions.

Is there anything that I could do to help get a new release out? My Nix-fu is sadly quite limited. :/

If a proper release is unlikely to happen in the short term, a Hackage revision that updates the version bounds would already be very helpful for me.

**Comment by jwiegley** [comment]
Before I can release, I need to be able to build, and at the moment `nix-build` of the current `master` fails in a confusing way. So alternatively, we could upgrade nixpkgs and Nix and our submodule of Nix, get that working, and then release. This would be better.

**Comment by sjakobi** [comment]
> Before I can release, I need to be able to build, and at the moment `nix-build` of the current `master` fails in a confusing way.

So https://github.com/haskell-nix/hnix/pull/521 didn't fix that? What's the error you're getting?

**Comment by sjakobi** [comment]
For the record: `nix-build` works for me on `master`.

**Comment by jwiegley** [comment]
@sjakobi I see the following: https://gist.github.com/50f33460325ded94aabb12f4391d88f8

**Comment by PierreR** [comment]
@jwiegley Not sure what is wrong or blocking but for information `prettyprinter-1.5` does seem to build fine for me on linux with the latest commit of nixpkgs (master/unstable channel).

FWIW The lack of release might make `dhallToNix` to fail with the same nixpkgs commit: see https://github.com/dhall-lang/dhall-haskell/issues/1624

**Comment by Anton-Latukha** [comment]
So. The `prettyprinter` was updated: `... < 1.6` and there recently was update of Nix submodule. If someone needs a release - this is probably the good moment.

**Comment by sjakobi** [comment]
Here's another update to the `prettyprinter` bound: https://github.com/haskell-nix/hnix/pull/535

A release would be great though – if only to simplify some dependency configurations in `dhall`.

**Comment by sjakobi** [comment]
Thank you! :)
