### ISSUE TITLE
x/* comment */ throws off parser

### ISSUE THREAD

**Issue by matthewbauer** [haskell-nix/hnix#53]
"all-packages.nix" currently has this edge case:

```nix
{
    hexdump = if stdenv.isLinux then utillinux.bin else vim/* xxd*/;
}
```

Nix understands this as a comment but hnix wants to turn it into a division operation, giving:

```
Parse failed: ErrInfo {_errDoc = pkgs/top-level/all-packages.nix:10657:61: error: expected: "/",
    slash
    hexdump = if stdenv.isLinux then utillinux.bin else vim/* xxd*/;           
                                                            ^                  , _errDeltas = [Directed "pkgs/top-level/all-packages.nix" 10656 60 333499 60]}
```

**Comment by jwiegley** [comment]
Note that this is covered by the Nix language tests, so I'm closing this as a separate issue. We're currently working on getting all of those tests to pass (down to 46 left, one of which is the full commenting test).
