### ISSUE TITLE
Missing documentation on Hackage

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#538]
Neither 0.7.0 nor 0.7.1 show haddocks on Hackage.

I suspect the problem are these build failures: http://hackage.haskell.org/package/hnix-0.7.1/reports/

```
main/Repl.hs:64:36: error:
    Ambiguous occurrence ‘options’
    It could refer to either ‘System.Console.Repline.options’,
                             imported from ‘System.Console.Repline’ at main/Repl.hs:56:1-39
                          or ‘Repl.options’, defined at main/Repl.hs:204:1
   |
64 |     $ evalRepl (return prefix) cmd options (Just ':') completer welcomeText
   |                                    ^^^^^^^

main/Repl.hs:221:48: error:
    Ambiguous occurrence ‘options’
    It could refer to either ‘System.Console.Repline.options’,
                             imported from ‘System.Console.Repline’ at main/Repl.hs:56:1-39
                          or ‘Repl.options’, defined at main/Repl.hs:204:1
    |
221 |   mapM_ putStrLn $ map (\o -> ":" ++ (fst o)) (options @e @t @f @m)
    |                                                ^^^^^^^
```

**Comment by sjakobi** [comment]
https://github.com/haskell-nix/hnix/pull/540 addresses the build failure.

**Comment by Anton-Latukha** [comment]
It seems like: https://github.com/haskell-nix/hnix/pull/580 already solved Haddock issue.

Its branch:
`upd-HNix-store-0.2: GHC 8.6.5, nix-shell`:

```fish
cabal v2-haddock
...
Documentation created:
/home/pyro/src/haskell/hnix/dist-newstyle/build/x86_64-linux/ghc-8.6.5/hnix-0.7.1/doc/html/hnix/index.html

cabal haddock
...
Documentation created:
/home/pyro/src/haskell/hnix/dist-newstyle/build/x86_64-linux/ghc-8.6.5/hnix-0.7.1/doc/html/hnix/index.html
```

**Comment by Anton-Latukha** [comment]
I've understood that `Repl.hs` is not in the build loop.
#582 should solve this. I've looked a bit into the usage of `HaskellineT/Repline` Hackage modules in `main/Repl.hs` other things seem not collide.

We should think how to include these files in the REPL IDE loop, so we can work on them.

**Comment by Anton-Latukha** [comment]
So to battle test fixes the Hackage prerelease is needed.

Soon we would be able to test this in CI.

**Comment by sjakobi** [comment]
The original issue has already been fixed in #582. Thanks again, @Anton-Latukha! :)

If there's more to do in this context, let's better track that in a different issue.

**Comment by Anton-Latukha** [comment]
There is a CI option ready to track these. Ther is the option (even several) to test full proper packaging.

**Comment by Anton-Latukha** [comment]
There are still no docs in 0.8.

That means we need to merge the CI, enable package testing and get on it.

**Comment by sjakobi** [comment]
Hackage currently reports that the docs build for [`hnix-0.8.0`](http://hackage.haskell.org/package/hnix-0.8.0) is still in progress: 

![image](https://user-images.githubusercontent.com/3664523/83327187-5bea1a00-a27a-11ea-92a8-2350603b0851.png)

However I don't expect it to succeed, since it already fails to build docs for `hnix-store-core` and `saltine`: https://github.com/haskell-nix/hnix-store/issues/65

We'll have to upload Haddocks manually for now. @jwiegley, could you take care of that, or give one of us permission to do it, i.e. add a maintainer on Hackage?

**Comment by Anton-Latukha** [comment]
Related #612, I've tried `buildFromSdist` and that is what resolves into.

**Comment by jwiegley** [comment]
@sjakobi I've added you as a Hackage maintainer for `hnix`. @Anton-Latukha What is your user id so that I may add you as well?

**Comment by Anton-Latukha** [comment]
@jwiegley Yes, I created the account `AntonLatukha`, received Hackage upload permissions, and would read-up upon Hackage docs.

**Comment by jwiegley** [comment]
@Anton-Latukha You're now a maintainer of hnix on Hackage, and can upload releases. Thank you!

**Comment by sjakobi** [comment]
I have found a bit of documentation on the manual docs upload here (see the "Notes" section at the bottom of the page):

http://hackage.haskell.org/upload

I've taken care of the missing docs for 0.7.0, 0.7.1 and 0.8.0 for now. I assume we'll have to do the manual upload with each release as long as `hnix-store-core` requires the libsodium system dependency (https://github.com/haskell-nix/hnix-store/issues/66).
