### ISSUE TITLE
Structure the code base with outshine (haddock struct) mode comments

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#555]
`outshine` and `haddock` structure blocks are the same thing.
`outshine` : https://github.com/alphapapa/outshine is current upstream
Outstanding blog post: https://www.modernemacs.com/post/outline-ivy/
Worg: https://orgmode.org/worg/org-tutorials/org-outside-org.html

Example: my Emacs `init.el` outline tree:
![Screenshot_20200519_220443-1](https://user-images.githubusercontent.com/20933385/82367744-f3e73880-9a1c-11ea-9d5d-9f69066858f4.png)

... so in several seconds - now you know the major part of what is in my Emacs config code base, and you roughly have a feel of the logical structure of the code.

It allows to achieve in one action:
  * commenting
  * structuring
  * outlining
  * easier to move arround in the code
  * and so easier to work with
  * also by hiding unnecessary code and concentration on the parts at hand - increases direction and concentration
  * allows to understand the codebase in seconds
  * allows to understand the codebase better and its structure
  * It allows structural editing by `org-mode` functions
  * by that it enables also easy structural editing / reorganization the source code
  * people who do not have or not use outshine would receive comments of the structure of the code - so they also straightly win from it.
  * by all that - it is more pleasent to code now
  * all this accelerates contributions, newcomers learn, contribute faster and better - because they have an understanding now.

And that is achieved just by commenting the blocks of the code.

I am learning how packaging currently done in the project, and `dafault.nix` craves for the `outshine`.

It is a win - win - win, `more win` practice. It is literate programming in `*.hs`, even more:
```
∀ Languages, ∀ Texts : ∃ {Commenting system, Outlining, Structuring, Literate programming}
```

It brings only benefits.

So I just straight would open PRs for it and link them here.

**Comment by Anton-Latukha** [comment]
In `nix-mode` and other modes where it does not work by layering comment symbols - the `outshine` works through the:

![Screenshot_20200519_224604](https://user-images.githubusercontent.com/20933385/82371324-abcb1480-9a22-11ea-9a51-19d7fb2e8160.png)

**Comment by Anton-Latukha** [comment]
Oh yes. Nix has a lot of `{..};` , so it interhal headlines inside it - the closing `}` should be in separate heading - I would use `# **** <-here is the space char`, so during structural any rearengements of the blocks - `}` is not grabbed without the knowledge of the person.

Basically once the person knows that inside `# **** ` there is just an `}` - it gets out of their counties into unconscious, since it represents new line, emptiness - since denotation with two chars `{` `}` - is in reality a syntatic sugar for one abstraction.

![Screenshot_20200520_000408](https://user-images.githubusercontent.com/20933385/82378210-6fe97c80-9a2d-11ea-8ba8-e6283f6d93c4.png)

**Comment by Anton-Latukha** [comment]
#### More explanation about why outshine is useful to the community

From raised question: https://github.com/haskell-nix/hnix/pull/556#issuecomment-631259580

I see laying out the structure of the code - not as useful personally "to me", I think more in benefits to the community, about other people and contributors at all, I see the structure useful to the community.

It teaches people, if someone does not knows something (everyone does not knows something) - outlining it helps them, they can see what that block is about - and with that direction, they start to properly understand it and so - learned it, it helps them also understand how things compose. And also saves thinking power to the experienced contributors that code - they able to see and read thoroughly blocks they need, and aslo concentrate only on them. Nix and Haskell have atomic modularity - so people indeed need to concentrate only on functions at the point.

The system is even is able to organize and guide a person in the infinite LOC file.

It is minimalistic literate programming. I've never heard anyone saying that literate programming was not understandable, I not even see why I should defend an argument.

Especially minimalistic literate programming that holds the astonishing balance being:
  * minimal in volume,
  * the most minimal in the effort
  * maximal in usefulness
  * maximally easy to maintain
  * maximally flexible and portable - it is useful to everyone.

**Comment by Anton-Latukha** [comment]
#### haddock vs. outshine

The haddocks are a tech doc specs, outshine is a headlines marking the structure of the code.

Haddock - technical documentation. Headlines have very general structural names of code sections. Aka `Org` headline is not haddock, an haddock is not a headline.

Is see only benefits having outshine & haddock - it is a collaboration between the two that would make the project a community gem to have jam party in. Anyone would be able to come and improve.

**Comment by sorki** [comment]
Can you link an example of the Haskell project using outshine? I'm curious how it looks combined with Haddocks and would like something to play with.

**Comment by Anton-Latukha** [comment]
I personally never encountered such sources, and I am too young a Haskell specialist (~2.5) to give a good example personal Haskell project. I use it for Emacs configuration that is public and in some private stuff.

It looks just like it does https://github.com/haskell-nix/hnix/pull/556 - there literally is nothing more to it in the sources. The blog post in the heading - provides the demonstrations.

If you use Emacs  - you can get Emacs configuration from mine or from the docs, or blog posts. It is basically just installing the package `outlshine` from MELPA and `outshine-mode` hook into `outline-minor-mode-hook` and that one hook into `prog-mode-hook` - and that should work already.

Then some useful stuff:
```elisp
;;;; Managing code with Outlines using =outshine=

  (add-hook 'outline-minor-mode-hook #'outshine-mode)

  ;; Enables outline-minor-mode for *ALL* programming buffers
  (add-hook 'prog-mode-hook #'outline-minor-mode)

  ;; Narrowing now works within the headline rather than requiring to be on it
  (advice-add 'outshine-narrow-to-subtree :before
              (lambda (&rest args) (unless (outline-on-heading-p t)
                                     (outline-previous-visible-heading 1))))

  (spacemacs/set-leader-keys
    ;; Narrowing
    "nn" 'outshine-narrow-to-subtree
    "nw" 'widen

    ;; Structural edits
    "nj" 'outline-move-subtree-down
    "nk" 'outline-move-subtree-up
    "nh" 'outline-promote
    "nl" 'outline-demote)

  (let ((kmap outline-minor-mode-map))
    (define-key kmap (kbd "M-RET") 'outshine-insert-heading)
    (define-key kmap (kbd "<backtab>") 'outshine-cycle-buffer)

    ;; Evil outline navigation keybindings
    (evil-define-key '(normal visual motion) kmap
      "gh" 'outline-up-heading
      "gj" 'outline-forward-same-level
      "gk" 'outline-backward-same-level
      "gl" 'outline-next-visible-heading
      "gu" 'outline-previous-visible-heading))
```

**Comment by Anton-Latukha** [comment]
I've met a couple of projects that have structure comments that may have been `outshine`, as also it works for comments that denote the structure.

I yet to meet a project opened in my Emacs when I have `outshine` there to make notice.

I know there exist same-stuff analogs in other editors.

**Comment by Anton-Latukha** [comment]
@sorki You are right.
`outshine` structure and `haddock` structure is the same thing ([haddock markup](https://cdn.rawgit.com/haskell/haddock/ghc-8.10/doc/cheatsheet/haddocks.svg)), so we in fact adding `haddock` structure here.

**Comment by Anton-Latukha** [comment]
So, what I requested is basically a Haddock markup already.
