### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#560]
The last minor was ~2-2.5 moths ago.
Many packages got an update in that time.

And we got a set of commits already.

Current diff available at: https://github.com/haskell-nix/hnix/compare/0.7.1...master

Diff looks minor, except for major change: https://github.com/haskell-nix/hnix/commit/f682907c97750338264d282a5a403a1cfc92fec8

What we bundled-in:
  * bump hnix-store-core 0.2 #537
  * default.nix: dep: upd hnix-store 0.2 #580
  * default.nix: clean-up old overrides #579
  * bump http-client-0.7 #596
  * Fix build failure in Nix.Var #587, it also freed from dependent-sum dependency
  * Repl.hs: import: Repline: resolving `options` collision #582
  * bump aeson to 1.5 #595
  * bump these to 1.1 #595
  * simplify evalExpression #547
  * bump pretty-show 1.11 #542 

We may bundle:
  * Clean up hashing-related dependencies #597
  * CI: Travis: upd: maybe this would be able to help #583

(postphoned, waiting on support from other projects) dep: upd time (1.9.3->1.10.0) #557
(postphoned, can wait) default.nix: add outshine comments structure #556

These merges conclude all currently needed Hackage dependency updates.

**Comment by Anton-Latukha** [comment]
Awaiting merges above.

**Comment by sjakobi** [comment]
It would be great if we could also address https://github.com/haskell-nix/hnix/issues/538 in time for this release.

**Comment by Anton-Latukha** [comment]
I've checked, #580 branch creates Haddock docks fine both `v1, v2`.
See https://github.com/haskell-nix/hnix/issues/538#issuecomment-633476668

**Comment by Anton-Latukha** [comment]
We got a release, new Report for next release #599

**Comment by Anton-Latukha** [comment]
It is great to see: https://matrix.hackage.haskell.org/#/package/hnix

... but still no docs: https://hackage.haskell.org/package/hnix
