### ISSUE TITLE
We may just get now and migrate into the Haskell/GitLab

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#575]
If we ever migrate - it is now.

What it would give us:

If we ever would be able to choose where to migrate - it is only now. Further if we evaluate NixPkgs - we lock-in.

  * Since the HNix is a Nix manager in Haskell - it is an important tool to the Haskell community in the future
  * We can host for example right inside https://gitlab.haskell.org/
  * Which brings us directly into Haskell community GitLab.
  * GitLab is MIT Licensed open to contributions and integrations project
  * GitLab has a nice Wiki engine that would allow us to create guidelines and gather knowledge there and educate people and they would learn. Solves: #568 
  * And all other automation which Haskell GitLab community can share around between themselves.
  * And all automation that GitLab allows
  * GitHub is closed proprietary project while GitLab is a proper open source project that is a massive versatile "DevOps lifecycle tool" suite that happens to be also a repository and a Wiki
  * And I am a former DevOps, so... we can automate staff there really good.
  * And all features that GitHub lack while Gitlab has. And it has A LOT of features.
  * Just look at how much is in the new GitLab release: https://www.youtube.com/playlist?list=PL05JrBw4t0KqWysAAKFYYIE2Tf9IZB5bv
  * GitHub lacks in some very obvious features. For me lack of some of them very is bizarre. It is still impossible to have a Project to autoload labels. Maintainer needs to label the issues and then search for those labels on the Reports select and drag them into the board - so maintainer needs to close the cycle of adding the issue to the tracking board - all the time by his hands, for every issue instead of that being automated. In the long run that is a lot of issues searching and dragging, so maintainers end-up always abandoning those and not managing any Kanbans.
  * While with GitLab it is automated from the get-go right at the Board creation:
![Screenshot_20200521_204543](https://user-images.githubusercontent.com/20933385/82589187-6f272680-9ba4-11ea-94d7-28d387175ecf.png)
  With that GitLab enables maintainers just to look at the Kanbans of their important stuff, for example some maintainer can maintain only new features, other - refactoring, other - security reports and PRs.
  * GitLab allows to migrate the project right now. And our project can fully migrate now. The longer we wait - the more we lock-in into the proprietary GitHub that follows a business will of the board of stakeholders.

Citation from: https://docs.gitlab.com/ee/user/project/import/github.html
> The following aspects of a project are imported:
> 
>   * Repository description (GitLab.com & 7.7+)
>   * Git repository data (GitLab.com & 7.7+)
>   * Issues (GitLab.com & 7.7+)
>   * Pull requests (GitLab.com & 8.4+)
>   * Wiki pages (GitLab.com & 8.4+)
>   * Milestones (GitLab.com & 8.7+)
>   * Labels (GitLab.com & 8.7+)
>   * Release note descriptions (GitLab.com & 8.12+)
>   * Pull request review comments (GitLab.com & 10.2+)
>   * Regular issue and pull request comments
> 
> References to pull requests and issues are preserved (GitLab.com & 8.7+), and each imported repository maintains visibility level unless that visibility level is restricted, in which case it defaults to the default project visibility.

Many open communities now migrated/in the process of migration to GitLab.
It seems now obvious that GitHub would have the mass advantage for along time and a lack of the needed features, when GitLab has an open structure, the huge feature set advantage, automation advantage, so everyone knows what would happen in the end. In the end all the tech enthusiasts would mostly end-up be on the GitLab side.

I know that the GitLab is not perfect, but it seems way better, it allows a way more automation, maneuvering, and abilities to manage the community processes.

---

Of course, my look has a mathematical bias, because I tend to see the GitHub design problems better. And I see that many of those solved in the GitLab. And the biased chosen subset of the only "errors" here for evaluation to be "Ok" needs to be translated just in a completely same subset of the only "errors" there, and that is a laughable requirement. I perceive translation into "successes" there. Since in IT systems there are more "success" states, then "error" states. And I tend to forget and overlook the "error" states in the GitLab.

Despite GitHub having responsiveness and I have the bias - from some experience I know that the GitLab is much more versatile in the maintenance & DevOps automation field, which would be helpful in the long run.

---

I want to discuss this.

**Comment by sjakobi** [comment]
In my experience https://gitlab.haskell.org/ghc/ghc has often been quite sluggish, more so than any GitHub projects I know. Apart from this concern I have a strong opinion on this issue.

**Comment by Anton-Latukha** [comment]
Yep, as you and I underlined GitLab is pretty slow.

And with all in Ruby it most probably would never be very responsive.

While GitHub backend is mostly in Haskell btw.

I am still balancing my position.

**Comment by Anton-Latukha** [comment]
The more I think about it the less and less I think we would migrate anywhere in the nearest time.

Also Nix/Nixpkgs/NixOS and DHall are on GitHub, so.
