### ISSUE TITLE
src/Nix/Var.hs error: Data constructor not in scope: Refl

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#585]
At the current `master` (93647246d10f2eedc2e9e2a38e942dd6b57267f9), I'm getting a build failure when building with

    cabal build -w ghc-8.6.5

and

    cabal build -w ghc-8.8.3

(without any Nix wrapping):

```
src/Nix/Var.hs:39:63: error: Data constructor not in scope: Refl
   |
39 |   a `geq` b = if a == unsafeCoerce b then Just $ unsafeCoerce Refl else Nothing
   |                                                               ^^^^

src/Nix/Var.hs:42:63: error: Data constructor not in scope: Refl
   |
42 |   a `geq` b = if a == unsafeCoerce b then Just $ unsafeCoerce Refl else Nothing
   |                                                               ^^^^
```

**Comment by sjakobi** [comment]
I think this is related to https://github.com/haskell-nix/hnix/commit/90d688747cc3756127948d4da45e54e17223ee87 – I can't reproduce it with the parent commit.

I've never seen `dependent-sum` before, but I get that the module that we [use](https://github.com/haskell-nix/hnix/blob/93647246d10f2eedc2e9e2a38e942dd6b57267f9/src/Nix/Var.hs#L11), `Data.GADT.Compare` is now re-exported from the `some` package.

We should probably drop the dependency on `dependent-sum` then, and figure out the correct bounds for `some`.

**Comment by sjakobi** [comment]
Apparently old versions of `dependent-sum` [re-exported `Refl`](http://hackage.haskell.org/package/dependent-sum-0.6.2.0/docs/Data-GADT-Compare.html#t::-126-:) from `Data.GADT.Compare`, but `some`'s `Data.GADT.Compare` doesn't.

**Comment by Anton-Latukha** [comment]
The module imports should be cleaned-up / qualified / constrained more.

We should make a gradual global cleanup of imports and modules.

Side note: Also I'd preferred to expand modularity of HNix much more, some files are 500-1000-1500 lines - for Haskell that is too long. Type into a module, Feature into a module.

Thank you. We have different build environments. I use `ghc` from `nix-shell` `/nix/store`.
I used my fresh shell function `nix-shell -> cabal v2-build ... ` it does not contain proper check keys - that is a pretty important mishap on my part. And current `master` CI tests on `8.2.2` with no `warn` keys (imagine). I currently refactor/updating the CI, so I would introduce needed checks there and into my current workflow in one go. So we would resolve things like this in the nearest time, and also would test on 3 recent GHC branches. Thank you.

**Comment by sjakobi** [comment]
#587 should fix this.

No worries, @Anton-Latukha! :)

If we increase CI coverage, ideally also using some constraint-solver based tool like `cabal`, we'll catch incompatibilities like this one much more easily.


> Side note: Also I'd preferred to expand modularity of HNix much more, some files are 500-1000-1500 lines - for Haskell that is too long. Type into a module, Feature into a module.

As long as compile times remain acceptable, large modules haven't caused me a lot of trouble so far. If you still want to go in that direction, we should try to keep the old modules re-exporting the same APIs, so users don't have to reshuffle their imports too much.

**Comment by Anton-Latukha** [comment]
Yes. The current module system is good already. I want over some long time to maximally preserving the API submodule those big files into smaller modules/files to sort the functionality better.

Also structuring with `outshine/haddock` would help to work on big files more easily.

Also IDEs loops would get a way more responsive and quicker, so the project would be even more quick and pleasantl to work with - the more modular project is. Because analysis/requilds are only on atomic modules changed.
