### ISSUE TITLE
Unused dependencies?

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#588]
In https://github.com/haskell-nix/hnix/pull/587 I noticed that the testsuite has a dependency on `dependent-sum` although that dependency was only used by the library. I'm wondering whether there are other dependencies that we could get rid of…

Once we support GHC 8.10, we can try [`-Wunused-packages`](http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-packages). Alternatively, try [`weeder`](http://hackage.haskell.org/package/weeder).

**Comment by sorki** [comment]
Wow, thanks for the tip! Ran it against lib, exe and test. Not sure why for exe/test we get the output twice.

``cabal build --ghc-options=-Wunused-packages lib:hnix``:

```
The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - semigroups-0.19.1
      - haskeline-0.8.0.0
      - dependent-sum-0.7.1.0
      - cryptohash-sha512-0.11.100.1
      - cryptohash-sha1-0.11.100.1
      - cryptohash-md5-0.11.100.1
      - contravariant-1.5.2
```
``cabal build --ghc-options=-Wunused-packages exe:hnix``

```
    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - hashing-0.1.0.1
      - cryptohash-sha512-0.11.100.1
      - cryptohash-sha256-0.11.101.0
      - cryptohash-sha1-0.11.100.1
      - cryptohash-md5-0.11.100.1
      - base16-bytestring-0.1.1.6

    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - template-haskell-2.16.0.0
      - serialise-0.2.2.0
      - ref-tf-0.4.0.2
      - hashing-0.1.0.1
      - data-fix-0.2.1
      - cryptohash-sha512-0.11.100.1
      - cryptohash-sha256-0.11.101.0
      - cryptohash-sha1-0.11.100.1
      - cryptohash-md5-0.11.100.1
      - bytestring-0.10.10.0
      - base16-bytestring-0.1.1.6
```

``cabal build --ghc-options=-Wunused-packages test:hnix-tests``

```
    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - tasty-quickcheck-0.10.1.1
      - serialise-0.2.2.0
      - hashing-0.1.0.1
      - generic-random-1.3.0.1
      - dependent-sum-0.7.1.0
      - cryptohash-sha512-0.11.100.1
      - cryptohash-sha256-0.11.101.0
      - cryptohash-sha1-0.11.100.1
      - cryptohash-md5-0.11.100.1
      - base16-bytestring-0.1.1.6

    The following packages were specified via -package or -package-id flags,
    but were not needed for compilation:
      - unordered-containers-0.2.10.0
      - transformers-0.5.6.2
      - template-haskell-2.16.0.0
      - tasty-quickcheck-0.10.1.1
      - serialise-0.2.2.0
      - mtl-2.2.2
      - hashing-0.1.0.1
      - generic-random-1.3.0.1
      - dependent-sum-0.7.1.0
      - cryptohash-sha512-0.11.100.1
      - cryptohash-sha256-0.11.101.0
      - cryptohash-sha1-0.11.100.1
      - cryptohash-md5-0.11.100.1
      - bytestring-0.10.10.0
      - base16-bytestring-0.1.1.6
```

**Comment by sjakobi** [comment]
Cool! Thanks for giving this a spin @sorki! :+1: 

A bunch of these dependencies seem to be related to this bit:

https://github.com/haskell-nix/hnix/blob/86b5da1fa1893055c12c416bc09081cd50b093b1/src/Nix/Builtins.hs#L34-L48

It would be nice to get this cleaned up, but I don't have the full picture right now. `hnix.cabal` hints at some conditionality on GHCJS:

https://github.com/haskell-nix/hnix/blob/86b5da1fa1893055c12c416bc09081cd50b093b1/hnix.cabal#L908-L919

But it still looks like the `cryptohash-*` packages are never actually used.

CI with GHCJS would be nice to have though. ;)

The best way forward would probably be to simply try to remove the dependencies. If some of these turn out to be necessary after all, possibly in some particular configuration, we'll eventually notice.

**Comment by Anton-Latukha** [comment]
When project would be clean from most unused deps - we would be able to flip a switch in CI to check for them.

I do not know if it is possible to strongly definitely check the deps. But we would be able to have a list of exceptions allowed there. I think that list would settle down into needed stuff pretty quickly.

There is a bunch of switches in incoming CI. After we do refactorings we would be able to switch the quality control on.

**Comment by sjakobi** [comment]
Motivated by [`cryptohash-sha512`'s incompatibility with GHC 8.10](https://github.com/haskell-hvr/cryptohash-sha512/issues/4) I've had another look at the related libraries.

* `hashing` says it's slow:

  > Performance wise it only has 1/5 - 1/15 of native C implementations, or cryptonite.

  And, somewhat surprisingly, `hnix` seems to be its only user: https://packdeps.haskellers.com/reverse/hashing

  Then again it's pure Haskell, while I suspect that most other libraries include C code and cannot be built with GHCJS.

* The `cryptohash-*` libraries should be faster, but have the problematic C code.

Since the performance of `hashing` doesn't seem to have caused any problems so far, and since it's compatible with GHC-8.10 and GHCJS, and because it addresses all our hashing needs in one package instead of 4, I think we should stick with it for now.

If performance turns out to be problematic, we can revisit the issue later.

**Comment by Anton-Latukha** [comment]
Yes.

I like the explanation and idea.

Indeed. Lets currently concentrate on project maintenance/maintainability. Indeed, there is no speed concern today - there is nothing to be faster, since Nix lang goes not evaluates fully. But there is a lot to clean-up and organize.

Great idea, we would more easily achieve and hold GHC 8.10 - that is of most importance in the nearest time.

Lets stabilize the dev now. We updated minor dependencies, and since it is GHC 8.10/JS related - lets make new release, merge the CI and go into GHC 8.10 head first.

**Comment by sjakobi** [comment]
#632 removed the remaining unused library dependencies. There are still some unused dependencies in the executable and testsuite components, but I believe all of these are also (transitive) library dependencies, so they don't really increase the size of the dependency tree.

**Comment by Anton-Latukha** [comment]
Thank you.

**Comment by sjakobi** [comment]
You're welcome, @Anton-Latukha! :)
