### ISSUE TITLE
Unbreak the HNix in Nixpkgs

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#591]
After a new release #560, please pay attention to unbreak the HNix in Nixpkgs.

**Comment by Anton-Latukha** [comment]
So, new release (0.8) happened.

I submitted Nixpkgs PR that cleans-up HNix package there.

**Comment by Anton-Latukha** [comment]
Indeed.
Now there is no override on old `these`.
Package respects dependency versions.
The package now is unbroken.

Also in the process, I found and fixed the shell completions generations in new `default.nix`.

The package still has `dontCheck`.

**Comment by Anton-Latukha** [comment]
PR just merged, good timing. :tada: - indeed. Now we are a normal Nixpkgs citizen.

**Comment by sjakobi** [comment]
Well done, @Anton-Latukha! :+1:

**Comment by Anton-Latukha** [comment]
Just logical progression.

If you would want to learn Haskel&Nixpkgs - there are Peti streams.
Since you are also a Haskell languages guy - it is pretty useful to at least know he merges&streams Friday UTC evenings: https://www.twitch.tv/peti343

Open PRs for Haskell-related updates on the `haskell-updates` branch in Nixpkgs. It is not consistent branch.

I submitted stuff yesterday, he merges everything and checks it all before merging into `master`.

**Comment by Anton-Latukha** [comment]
Reading `Nix pills`, then reading manual very hard while participating in Nixpkgs community, then watching Peti's video backlog - explains the Haskell&Nixpkgs.
