### ISSUE TITLE
Please, support GHC 8.8/8.10

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#592]
I am currently enabling in the CI the builds with GHC JS/8.8/8.10.

Soon, would report what CI tells us.

Monitoring status:
GHC:
  :heavy_multiplication_x: JS
  :heavy_check_mark: 8.6.5
  :heavy_check_mark: 8.8.3
  :heavy_multiplication_x: 8.8.10

**Comment by Anton-Latukha** [comment]
8.10.1 [CI log](https://travis-ci.org/github/haskell-nix/hnix/jobs/691255214):
<details><summary>wrapper</summary>
<p>

```
Configuring cryptohash-sha512-0.11.100.1...

CallStack (from HasCallStack):

  $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.0.0:Distribution.Simple.Configure

  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.0.0:Distribution.Simple.Configure

  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.0.0:Distribution.Simple

  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.0.0:Distribution.Simple.UserHooks

  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.0.0:Distribution.Simple

  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.0.0:Distribution.Simple

  defaultMain, called at Setup.hs:2:8 in main:Main

Setup: Encountered missing or private dependencies:

base >=4.5 && <4.14

builder for '/nix/store/6qz9n3yxnfsycnyciqc58ap67y8zdm7w-cryptohash-sha512-0.11.100.1.drv' failed with exit code 1
```
</details>

**Comment by sorki** [comment]
There's few doJailbreaks needed for 8.10.1, see https://github.com/sorki/hnix-overlay/blob/master/overlay.nix#L35

I've only PRed `lens-family-th` fix so far as that was the most pressing one.

**Comment by Anton-Latukha** [comment]
I think the Haskell stack has a worse state this week, because `peti` skipped last Friday maintenance.
So without him some PRs not merged in a week, and some packages people came and marked broken and so on.

We should be able to bring things into a normal state after this Friday until next.

**Comment by sjakobi** [comment]
I see at least two more things that we ought to address for proper GHC 8.10 support:

* [x] Try getting rid of the `cryptohash-sha512` dependency which has a `base < 4.14` bound: https://github.com/haskell-hvr/cryptohash-sha512/issues/4
* [ ] Fix the `instance Lift (Fix NExprF)`:

    ```
    src/Nix/Expr/Types.hs:141:10: warning: [-Wmissing-methods]
        • No explicit implementation for
            ‘liftTyped’
        • In the instance declaration for ‘Lift (Fix NExprF)’
        |
    141 | instance Lift (Fix NExprF) where
        |          ^^^^^^^^^^^^^^^^^
    ```

**Comment by sjakobi** [comment]
> * [ ]  Try getting rid of the `cryptohash-sha512` dependency which has a `base < 4.14` bound: [haskell-hvr/cryptohash-sha512#4](https://github.com/haskell-hvr/cryptohash-sha512/issues/4)

https://github.com/haskell-nix/hnix/pull/597 addresses this.

**Comment by mightybyte** [comment]
> Try getting rid of the cryptohash-sha512 dependency which has a base < 4.14 bound

Alternatively, how about an upstream PR bumping bounds in `cryptohash-sha512`?

**Comment by sjakobi** [comment]
> Alternatively, how about an upstream PR bumping bounds in `cryptohash-sha512`?

I preferred to use `hashing` only for now. See https://github.com/haskell-nix/hnix/issues/588#issuecomment-634692400 for my reasoning. Comments are very welcome! :)

Also, hvr can sometimes be quite slow to merge PRs. Right now I'm trying to achieve GHC 8.10 compatibility rather sooner than later.

**Comment by Ericson2314** [comment]
We can use forks of packages and override via nix---we should never be dissuaded from not forking because of upstream being slow to respond.

**Comment by sjakobi** [comment]
Yeah. Personally, I want to use `hnix` with `cabal`, ideally out-of-the-box, and without non-Hackage dependencies.

**Comment by sjakobi** [comment]
I could use some help with the `Lift` instance:

https://github.com/haskell-nix/hnix/blob/726dc96b053001554eacdcc3991a8cde319ffa79/src/Nix/Expr/Types.hs#L141-L145

I've looked at the [migration guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/8.10#lift-changes), but haven't found a suggestion how to replace our use of `dataToExpQ`.

I've tried deriving, but without success:

```
src/Nix/Expr/Types.hs:142:1-35: error:
    • No instance for (Lift (NExprF (Fix NExprF)))
        arising from a use of ‘lift’
    • In the expression: lift a1
      In the expression:
        [| Fix a1 |]
        pending(rn) [<a1, lift a1>]
      In an equation for ‘lift’:
          lift (Fix a1)
            = [| Fix a1 |]
              pending(rn) [<a1, lift a1>]
      When typechecking the code for ‘lift’
        in a derived instance for ‘Lift (Fix NExprF)’:
        To see the code I am typechecking, use -ddump-deriv
    |
142 | deriving instance Lift (Fix NExprF)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Admittedly, I'm not particularly experienced with template haskell, nor with `Fix`! :/

@ryantrinkle You've added that instance a while back in https://github.com/haskell-nix/hnix/commit/8b0de962b055bd73393849aaa64d8957fc393200. Any ideas?

If we can't fix it soon, we could consider leaving `liftTyped` unimplemented, or define it with `error` for now to silence the warning…

**Comment by Anton-Latukha** [comment]
CI is merged. Currently, its builds gain relevant cache.

You can look at the GHC 8.10 CI build errors and follow them.

Build should be an optional build, because GHC 8.10 build breaks for now - if it would be set mandatory it would break statuses of all PRs with unrelated error to the PR changes.

**Comment by Anton-Latukha** [comment]
`Fix` is a recursive scheme rudiments, essentially if we do stuff properly - there should be less and less `Fix` the further we go, John already done a major work fighting through terrible recursive schemes bottleneck and we now on the reap fruits side.

**Comment by Anton-Latukha** [comment]
Congratulations - we have CI builds of GHC 8.10 already succesfull: https://travis-ci.org/github/haskell-nix/hnix/jobs/692755948

**Comment by Anton-Latukha** [comment]
It is funny, seems like in `nixpkgs-unstable` something was reverted, so an hour later we no longer building with GHC 8.10 due to dependencies not being solved.

**Comment by Anton-Latukha** [comment]
Since it is already an issue - maybe the it is better to move to `nixos-unstable` then?

**Comment by Anton-Latukha** [comment]
Nevermind. Sorry to rush with the report and hijack a bit.

It is Nix interpreter bug:

<details><summary>wrapper</summary>
<p>

Since Nix got an update, now it seems happy to report "All done" success on error throws:

```
Configuring lens-family-th-0.5.0.2...

CallStack (from HasCallStack):

  $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.0.0:Distribution.Simple.Configure

  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.0.0:Distribution.Simple.Configure

  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.0.0:Distribution.Simple

  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.0.0:Distribution.Simple.UserHooks

  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.0.0:Distribution.Simple

  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.0.0:Distribution.Simple

  defaultMain, called at Setup.hs:2:8 in main:Main

Setup: Encountered missing or private dependencies:

base >=4.9 && <4.14, template-haskell >=2.11 && <2.16

builder for '/nix/store/qkcjhnd693w9w1ssksjxzx1y7126p058-lens-family-th-0.5.0.2.drv' failed with exit code 1

cannot build derivation '/nix/store/66d6jcb7m9hm6c9acwc880rmqgr1r36a-hnix-0.8.0.drv': 1 dependencies couldn't be built

error: build of '/nix/store/66d6jcb7m9hm6c9acwc880rmqgr1r36a-hnix-0.8.0.drv' failed

All done.
```

And in other 50% of cases:
```
Configuring lens-family-th-0.5.0.2...

CallStack (from HasCallStack):

  $, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:1024:20 in Cabal-3.2.0.0:Distribution.Simple.Configure

  configureFinalizedPackage, called at libraries/Cabal/Cabal/Distribution/Simple/Configure.hs:477:12 in Cabal-3.2.0.0:Distribution.Simple.Configure

  configure, called at libraries/Cabal/Cabal/Distribution/Simple.hs:625:20 in Cabal-3.2.0.0:Distribution.Simple

  confHook, called at libraries/Cabal/Cabal/Distribution/Simple/UserHooks.hs:65:5 in Cabal-3.2.0.0:Distribution.Simple.UserHooks

  configureAction, called at libraries/Cabal/Cabal/Distribution/Simple.hs:180:19 in Cabal-3.2.0.0:Distribution.Simple

  defaultMainHelper, called at libraries/Cabal/Cabal/Distribution/Simple.hs:116:27 in Cabal-3.2.0.0:Distribution.Simple

  defaultMain, called at Setup.hs:2:8 in main:Main

Setup: Encountered missing or private dependencies:

base >=4.9 && <4.14, template-haskell >=2.11 && <2.16

builder for '/nix/store/qkcjhnd693w9w1ssksjxzx1y7126p058-lens-family-th-0.5.0.2.drv' failed with exit code 1

cannot build derivation '/nix/store/jc8nbqsgnk9ph48kj0m4dgqpp1m0bzfr-hnix-0.8.0.drv': 1 dependencies couldn't be built

error: build of '/nix/store/jc8nbqsgnk9ph48kj0m4dgqpp1m0bzfr-hnix-0.8.0.drv' failed

The command "if [ ! "$GHCVERSION" = 'ghcjs' ]; then ./build.sh; fi" exited with 100.
```


</details>

**Comment by sorki** [comment]
Looks like `lens-family-th 0.5.1.0` landed in master already as `lens-family-th_0_5_1_0`.

**Comment by Anton-Latukha** [comment]
Sorry for the inconvenience.

CI tests of PRs work properly. **Optional** GHC 8.10 build-in PRs work properly.

In `master` thou, in inside repo branches - optional `GHC 8.10` currently passes green when build fails.

I would solve that in the nearest time.

**Comment by Anton-Latukha** [comment]
https://github.com/haskell-nix/hnix/issues/592#issuecomment-636293125 gosh, how this practice is inconvenient. Instead of Nixpgks going straight in with automatic switching/total migration. Every unique one needs to solve this issue themself, and then look when to switch back.

We can not solve all Nixpkgs. For Haskell case - `hackage2nix` it is possible to account for support state through versions through bounds.

**Comment by Anton-Latukha** [comment]
Release `0.9.0` uploaded.

Now project release also available under GHC 8.10

Hackage Matrix: https://matrix.hackage.haskell.org/#/package/hnix

**Comment by Anton-Latukha** [comment]
Seems `lens-family-th` Nixpkgs issue got resolved upstream and tricked-down into `nixpkgs-unstable`.

Now project under GHC 8.10 & Nixpkgs builds trivially.

**Comment by sjakobi** [comment]
@Anton-Latukha Can this be closed now?

The `liftTyped` issue is of course unresolved, but it's rather hidden in this thread and a very apparent problem to anyone who tries to use `liftTyped`, so I'm not even sure it needs to have an own issue.

**Comment by Anton-Latukha** [comment]
Oh, I already forgot that I am the one who opened this one.

Thank you, this was a great collaborative work.

Case was solved.
