### ISSUE TITLE
Find a CI that is able to pass multiple check results into GitHub

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#593]
Travis and most others CIs not even able to show multiple checks into GitHub.

CI should report to GitHub what builds are passed, good if show the short log/err message.

GHC platform and versions, warning checks, HLint, Haddock coverage... etc should be separate checks instead of ONE that CIs think is enough.

Even I myself used to configure private Hydra in 2017 to pass multiple checks into GitHub.

**Comment by Anton-Latukha** [comment]
And after recent company acquisition and firing the team: https://www.reddit.com/r/devops/comments/at3oyq/it_looks_like_ibera_is_gutting_travis_ci_just_a/

And with everyone migrating from Travis CI onto GitHub CI.

I do not think that Travis CI has any future, we need to migrate to better CI, with better possibilities and docs in the nearest time.

**Comment by sjakobi** [comment]
@Anton-Latukha That Reddit post is well over a year old by now. Travis certainly isn't perfect but it's still widely used and I thought it was working fairly well for this project after all the work you've put into it.

What's the motivation for switching to something else now?

**Comment by Anton-Latukha** [comment]
@sjakobi 

I made the setup so it is most portable.

Haskell.Lib API is dragged and available at the every step:
Haskell packages Nixpkgs -> `default.nix` -> `build.sh` -> `.travis.yml`

And API is seamless.

Mojor part of build logic is in `build.sh` and it is universal portable between CIs.

Most CIs has a lack of very important feature - they pass only one check report, they can not pass multiple checks.

For example look at any Nixpkgs PR: https://github.com/NixOS/nixpkgs/pull/90195

Hydra CI and other advanced CIs can report multiple separate checks into the status.

AKA, build status for every platform/case, status of warnings, dependency status checks, lint report status, our custom checks... and so on, so everyone receives detailed info on the PR and current code status.

I done Travis and observed it as a product many years, it is mostly stalled and underfunded, docs are still lack clarity, for a number of years I know it is better to move to other CIs.

**Comment by sjakobi** [comment]
Yeah. Having GitHub report the status on multiple checks sounds nice to have, although I haven't particularly missed it so far.

My main issue with Travis in the past few months was that, sometimes, the CI status wouldn't show up at all. I received [some advice](https://github.com/haskell-CI/haskell-ci/issues/377#issuecomment-609402121) for a workaround for this, but I haven't actually tried using it.
