### ISSUE TITLE
Please, refactor `Control.Monad.Fail`

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#613]
`GHC 8.8` complains about them.
And since Nix is not a Cabal, no:
```haskell
#if __GLASGOW_HASKELL__ < 880
import           Control.Monad.Fail
#endif
```

But `GHC 8.{4,6}` require it, please refactor so there is no `Control.Monad.Fail`/`MonadFail`.

That would remove warnings in `GHC 8.8`.

**Comment by sjakobi** [comment]
Sounds tricky to me, but I haven't looked at the relevant code yet.

Does Nix support none of the usual CPP macros or just not that one? In this specific case we could also use

```
#if !MIN_VERSION_base(4,13,0)
import …
#endif 
```

… or similar…
