### ISSUE TITLE
Please, provide and enable `failOnAllWarnings` builds in CI on the newest GHC possible

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#614]
Reminder to establish these checks after #611 merges.

**Comment by sjakobi** [comment]
Warnings with older GHC versions are mostly uninteresting in my experience. Nothing worth worrying about usually.

OTOH with more recent GHC versions, there tend to be more interesting warnings. Such as the one for [the missing `liftTyped` definition](https://github.com/haskell-nix/hnix/issues/592#issuecomment-634665426).

**Comment by Anton-Latukha** [comment]
Well the idea is:

The project still can not enable the `failOnAllWarnings` for `GHC 8.{8,10}`, because of `MonadFail` warnings in them.
But now project CI can enable `failOnAllWarnings` for `GHC 8.{4,6}` and guard warning there. Yes, those are older versions, but their set of warning cases almost fully included into never GHCs.

So idea is to enable `failOnAllWarnings` at least in old GHCs. So it would guard project from the introduction of new warnings, so we would be able to clean warnings that are already in the code, and so we would be able to put `failOnAllWarnings` onto newer GHC, and more forward.

But you also your argument is right. It is ideal that only newer GHC guards with warnings. That is the state of the project and CI that project must head towards, and currently I try to guard in it what project allows and what we can guard, so we more easily would be able to gradually raize the guards to the proper places.

**Comment by Anton-Latukha** [comment]
So you are right, it is enough to guard on one required build, and it should be the newest GHC possible.

**Comment by Anton-Latukha** [comment]
Done in #625
