### ISSUE TITLE
Please, print Nix data types using `pretty-simple` package

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#619]
`cdepillabout` created a beautiful package https://github.com/cdepillabout/pretty-simple that is ideal for `hnix`.

**Comment by sjakobi** [comment]
`pretty-simple` is a nice package indeed.

Could you clarify where you think it ought to be used in `hnix` though?

**Comment by Anton-Latukha** [comment]
Nix REPL has the obvious ability to print the evaluated result.

Example:

```nix
nix-repl> lib = import <nixpkgs/lib>
               SET = with lib; {
               EDITOR = [ "VAL" ];
               } // {
               EDITOR = lib.mkIf false [ "TRUE" ];
               }


# :p <expr>     Evaluate and print expression recursively

# Evaluating, printing result:

nix-repl> :p SET           
{ EDITOR = { _type = "if"; condition = false; content = [ "TRUE" ]; }; }

nix-repl> :p SET.EDITOR
{ _type = "if"; condition = false; content = [ "TRUE" ]; }
```

As you can see the Nix REPL printing is not pretty-printed.

`cdepillabout` is a major Haskell Nixpkgs maintainer. And I noticed that his `pretty-simple` already from the start prints the information in a good Nix pretty-printed way.

HNix REPL as REPL needs this major feature of printing out the data. As you remember I talked about that store expected to have many type inconsistencies, so this feature needed to even be able to advance the project and for HNix to have meaning. 

From words of `peti` strong typing is the main strong technical and selling point of HNix for Nixpkgs ecosystem. Since Nix lang and processes are somewhat obscure - many major maintainers in the Nix ecosystem and DevOps'es that deploy Nix stack - use REPL daily to check and look into the code and processes. If work in HNix REPL and its output would be prettier - even more so, HNix would not only win some points evaluating the store, but would attract some good store maintainers and DevOps'es to use it.

So it is needed so people can debug the Nixpkgs and look inside Nix language processes. And only HNix REPL and printing of the data contents would help to solve those, and at the same time HNix meaning depends upon the REPL reporting Nix lang type errors in a meaningful way, so HNix would be able to iron the type errors and evaluate the Nixpkgs.

**Comment by Anton-Latukha** [comment]
HNix REPL needs major work.

**Comment by sjakobi** [comment]
Ok, I see that the `nix-repl` output could be a bit nicer. It uses our own prettyprinter (`Nix.Pretty`) though, right?

I think `pretty-simple` wouldn't really help us in this context since it's made to improve the output of Haskell's `show` function, which is primarily intended for debugging Haskell data structures. I don't think `pretty-simple` could handle Nix syntax.

**Comment by Anton-Latukha** [comment]
Done.
