### ISSUE TITLE
Parser breaks on EOF (end of comment)

### ISSUE THREAD

**Issue by domenkozar** [haskell-nix/hnix#62]
```
Parse failed: ErrInfo {_errDoc = ./pkgs/os-specific/linux/systemd/default.nix:194:1: error: unexpected
    EOF, expected: end of comment
<EOF>
^     , _errDeltas = [Directed "./pkgs/os-specific/linux/systemd/default.nix" 193 0 7291 0]}
```

**Comment by ryantrinkle** [comment]
This looks related to [parse-okay-crlf](https://github.com/ryantrinkle/nix/blob/f2273b11f5aec82fd4546aff6ff621aeb397f794/tests/lang/parse-okay-crlf.nix) and [parse-okay-comments](https://github.com/ryantrinkle/nix/blob/f2273b11f5aec82fd4546aff6ff621aeb397f794/tests/lang/parse-okay-comments.nix)
