### ISSUE TITLE
Try getting rid of the dependency on the interpolate package

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#634]
This is a package dependency graph for `hnix`, produced with `stack dot --external | dot -Tpng hnix.png` and this `stack.yaml`:

```
resolver: lts-16.1
extra-deps:
- hashing-0.1.0.1@sha256:98861f16791946cdf28e3c7a6ee9ac8b72d546d6e33c569c7087ef18253294e7,2816
- hnix-store-core-0.2.0.0@sha256:1c52ed924ca51130e3850d7f793975b98995da0fba57b15a81e73918921e0caf,2651
- monadlist-0.0.2@sha256:978305e3f03dd5f65c673b551124dac0c39a247c2c14d84739ca9a3405fbb63a,904
- ref-tf-0.4.0.2@sha256:69de3550250e0cd69f45d080359cb314a9487c915024349c75b78732bbee9332,1134
```

![hnix](https://user-images.githubusercontent.com/3664523/85080959-e4e5d880-b1ca-11ea-9560-9c88b906fbab.png)

If you look at the right border of the image, you see a dependency chain `interpolate -> haskell-src-meta -> haskell-src-exts`.

`haskell-src-exts` is notorious for being undermaintained and taking ages to compile. If we could get rid of `interpolate`, we could also shed this dependency.

To replace `interpolate` we could try using [`neat-interpolation`](http://hackage.haskell.org/package/neat-interpolation), which would AFAICT incur no additional dependencies. I'm not too familiar with either package, but I know that `dhall` uses `neat-interpolation` too.

**Comment by Anton-Latukha** [comment]
That is some SWAT work dude.

**Comment by Anton-Latukha** [comment]
I not used `stack` in years. AFAIR this seems to be Graphviz kind of graphs. 

Graphviz files can be imported into Gephi, well, may things can be imported into Gephi, and I used to use different untangling, clustering, Atlas2 on graphs like this.

I used to love to visualize the whole stores. I think today cool features like this, there should be web service to look at Haskell ecosystem or Nixpkgs closures, or even provided on Hackage for dependency monitoring. WebGL can easily draw huge complex graphs.

**Comment by sjakobi** [comment]
I haven't come up with this idea by looking at the graph BTW. I was rebuilding `hnix` and noticed that we're building `haskell-src-exts`, which just seemed like a bad idea so I investigated a bit.

`stack dot` does indeed produce output for Graphviz. It uses `ghc-pkg dot` under the hood, so there are probably other tools that can produce these package graphs too – I was just familiar with this one.

Gephi looks cool, but I'm too lazy to try to install it right now. I'm on Ubuntu :(

**Comment by Anton-Latukha** [comment]
Most days of my life I wish my desktop was on Ubuntu.

NixOS is very rough this year.

Gephi is a major software, it should be available for Ubuntu.

---

I used to like Gephi to watch closures, dependency graphs in code and Linux package project dependencies, Docker images dependencies, build a graph of surrounding nodes for something.
