### ISSUE TITLE
Please, include maintainers of this repositories into the `haskell-nix` group

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#636]
I would be straight with this request.

1. There is only 2 projects in `haskell-nix` group, `hnix` and `hnix-store` and they are intertwined projects, they work on the single goal.
2. We are people currently active and speeding-up the processes back.
3. `hnix-store` needs to be maintained better, currently, it feels very much as there is no maintainers.
4. `hnix-store-remote` does not build in Nixpkgs for some time, nobody addresses that.
5. The `hnix-store` project at least needs CI to be able to claim, be sure of stability, especially relating to Nixpkgs, maintainers would see the Nixpkgs build problem if there is CI in the project at least.
6. There are contributors and PRs ready to be merged into `hnix-store` [[1]](https://github.com/haskell-nix/hnix-store/pulls), I know that people have trouble to get  code reviewed and more importantly - merge into the repository. Contributors to the repository should be accepted and their work should be cherished by quick responces.
7. While `hnix-store-remote` is broken in Nixpkgs, there are people making active work on `hnix-store-remote`, but they are out of the tree and try to merge it: https://github.com/haskell-nix/hnix-store/pull/59, https://github.com/haskell-nix/hnix-store/pull/63/
8. For example, https://github.com/haskell-nix/hnix-store/pull/60/files is easily mergeable, but it is not merged in more than three months (Mar 12).
9. Last change accepted into `hnix-store` was almost 3 months ago (Mar 28)
10. Overall there is number of people that should be able to maintain the `hnix-store`, and I am up for extending roasters both there and here. @imalsogreg @layus and @sorki are good specialists that can handle the responsibilities in `hnix-store` and I trust them to work with them in `hnix` also.

---

11. I want to move HNix CI. Since currently Travis check and status in PRs sometimes disappear or does not update - I want to at least do a minor migration from Travis CI `.org` into never Travis-GitHub API engine that is on `.com`, detailed explanation: https://github.com/haskell-CI/haskell-ci/issues/377#issuecomment-609402121. With membership into the group account, I could've long ago click the button to migrate it. Since I did major work for CI recently and I maintain the CI now it seems logical that it is my responsibility to maintain it and to migrate the CI, so check reports work always.
12. Overall Travis is buggy and restrictive. I can easily migrate the `hnix` project to better CIs and work on the CIs automations, for example #593, #581, I can deploy Hydra for the group, but as always, the group account access is needed to click the button to provide the access hook for any CIs or services.
13. There is also a low service limits for anonymous free shields update statuses, the front page of the `hnix` sometimes (for example 3 days span on this week) reported CI `build error`, while in fact the contrary was true - statuses of consistent merges into `master` CI builds were always green, the shield was showing the wrong status due to update limits. To get much bigger shield update limits - i've could just click a button to register.
14. For example, soon due to [upstream Hackage work there would be more possibilities for monitoring](https://summerofcode.withgoogle.com/projects/#4737502172151808). CI monitoring also can/should report more info of statuses to the front page. For example documentation coverage of the project, closure size so we can monitor them. It needs registering the group and increasing badge limits.
15. There are other services (security scanning) and I have/there are possible processes automation ideas that the projects can benefit from, those services need hooks setup to the repository.

---

16. In `haskell-nix` https://github.com/haskell-nix/hnix-repl can be cleaned-up.
17. Active maintainers in `hnix` have and produce projects that by theme and idea belong into the `haskell-nix` group.
18. For example, I want to share with Haskell community with the `hnix` CI setup that uses Nix configuration (#637). Since it is drop-in, intuitive, versatile and portable to any CIs. When I form a repo in `haskell-nix` or in my identity account - I would be happy to receive improvements, suggestions. I want to add build presets, generalize the structure even more, maybe form an API extension to project package, add IOHK `haskell.nix` support.
19. In future there would be more effective ideas & projects.
20. Other maintainers also have their great projects that fit into `haskell-nix` group. From some of those projects, the `HNix` and `HNix-store` can benefit directly. And if they would be kind enough they might share some of them into the group.
21. I see only a good step in extending the `haskell-nix` group with active project maintainers, this extends the maintenance abilities, officialize the maintainer status and rewards/motivates people.

Already BlackJack.

Probably I stated too much points, if something, I can give more.

Calling the group: @haskell-nix

**Comment by sorki** [comment]
I've contacted Shea and got access to `hnix-store` few hours ago, had to run from the computer so failed to shared the news. 

I think @imalsogreg has access already and :+1: for @layus as well.

**Comment by Anton-Latukha** [comment]
Ok, @sorki, you never failed, you contribute, and we have lives.

Better for GitHub to have the ability to show the maintainers for the projects, contributors, and maintainers, should be provided with the ability to see the maintainers list of the projects if the projects wishe to share it.

**Comment by Ericson2314** [comment]
> Better for GitHub to have the ability to show the maintainers for the projects, contributors, and maintainers, should be provided with the ability to see the maintainers list of the projects if the projects wishe to share it.

The issues is team membership is private by default, and most people don't bother to change the setting I think because they do not know about it.

**Comment by Anton-Latukha** [comment]
Ok. Since no one addresses the topic.

I and maintainers have no choice and required to create the related projects elsewhere.

Because there was no response from anyone addressing the topic of discussion even partially, because of that I need to continue with #637 forming repository `haskell-nixpkgs-ci` separately and would curate and work on it in my private account.

**Comment by sorki** [comment]
I agree that it would be nice to be able to include other projects and their maintainers in this group. I've recently suggested this to `expipiplus1` regarding `update-nix-fetchgit` who thinks it's a good idea. We can set-up teams for the projects so global access is not an issue.

This would also provide some visibility for `hnix` based projects and allow us to coordinate releases more easily. I was recently looking at `hnix` based project list and there's quite a few projects already, some listed at https://packdeps.haskellers.com/reverse/hnix and few others not published on Hackage like `hnix-lsp` or `nixos-manager`.

Is there someone from haskell-nix owners group who wouldn't mind acting as a contact person for this? Could be done publicly via some meta issue here or even separate repo for organizational purposes.

**Comment by Anton-Latukha** [comment]
I perceive that most groups do not grow properly, they often have several people in them, and so they only have one-two active projects and groups abandoned quite frequently. Rarely you observe the groups that decide to be more open and becoming alive big social group.

Yes. Gathering projects under one roof is beneficial.

As you, people arriving at the projects always wondering how good, useful, developed they are, and the main thing - does this project longterm and under stable roof and is it worth to discern it and learn, lean/rely/use it.

Of course when the project in the personal account, creates a private staple on it, and project has a harder time growing until it becomes a brand that is self-evident and people would overlook that essentially one person curates and has the power over it.

The group accounts are about community work and community maintenance of the projects.

When any contributor arrives, at some project, one looks at the group account with an understandable name. The group projects also indicate that they integrate or even go together. And contributor sees a number of effective and active projects that directly correspond to the theme. And sees that they are alive, and gets excited. He just found a real community on the interesting theme to him. You can hear a person: "Oh, what a great place, I want to look in and learn about all these interesting useful projects to me. They not home-baked private use repos, but really projects used and cared for by many. And it seems as an alive dope place to participate." And there is just some time until a person contributes and the community becomes even more alive, and growth and development happens.

Also group then really becomes a brand, so others recognize the place and go to it steadily, propose new projects into it, and transfer projects into it.

**Comment by jwiegley** [comment]
@Anton-Latukha You and the others who had Maintain access to this repository are all invited as owners of the `haskell-nix` organization.

**Comment by Anton-Latukha** [comment]
Thank you. Now we have an additional degree of possibilities for the automation of the project processes/services and evolution, bring in projects etc. Thank you. Solved.
