### ISSUE TITLE
No explicit implementation for ‘liftTyped’ In the instance declaration for ‘Lift (Fix NExprF)’

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#652]
https://github.com/haskell-nix/hnix/blob/529f950696bb111356e0a8571941e49aea3a6204/src/Nix/Expr/Types.hs#L141-L145

currently produces the following warning when building with GHC 8.10:

```
src/Nix/Expr/Types.hs:141:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘liftTyped’
    • In the instance declaration for ‘Lift (Fix NExprF)’
    |
141 | instance Lift (Fix NExprF) where
    |          ^^^^^^^^^^^^^^^^^
```

**Comment by sjakobi** [comment]
https://github.com/haskell-nix/hnix/issues/592#issuecomment-634755479 describes a previous attempt to fix this.

In https://github.com/haskell/text/pull/290 I came across another way:

```
#if MIN_VERSION_template_haskell(2,17,0)
  liftTyped = TH.unsafeCodeCoerce . TH.lift
#elif MIN_VERSION_template_haskell(2,16,0)
  liftTyped = TH.unsafeTExpCoerce . TH.lift
#endif
```

See the documentation for `unsafeTExpCoerce`: http://hackage.haskell.org/package/template-haskell-2.16.0.0/docs/Language-Haskell-TH-Syntax.html#v:unsafeTExpCoerce

I'm not sure though whether this would be a good approach for `NExpr` too…

**Comment by Anton-Latukha** [comment]
Was done.

 Remembering that `layus` submitted lifted instance.

GHC 8.10 Nix build currently holds strict testing.
