### ISSUE TITLE
Please, provide an executable with GHC 8.10 in Nixpkgs

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#656]
Currently the default package for HNix `0.9.0` in `haskell-updates` is without an executable, because Nixpkgs default is 8.8.3.

I would go downstream and would try to negotiate the HNix shipment with GHC 8.10 in the closure.

Since that is also a future-proofing, Nixpkgs and we anyway would roll onto GHC 8.10, and executable status would most probably be as true case then as it is now.

**Comment by Anton-Latukha** [comment]
Well, since executable is in a bad state, maybe we need to worry about that more, at the moment there is almost no sense in shipping it.

I again arrived at the same conclusion I arrived at in #328

**Comment by sjakobi** [comment]
> executable is in a bad state

What are the problems with the current state? Do we have tickets that track them?

**Comment by Anton-Latukha** [comment]
Well, it is very simple, Nixpkgs defaults to 8.8.3, so no executable for us there.
Or we need to negotiate GHC overload (->8.10) for us, which would mean we would sneak a whole stack (maybe a couple of GBs would suddenly get into our "default" closure for many of our users).

In time forming a separate executable - should solve this properly, then we can say - that people opted-in to have the binary, so lets send GHC 8.10 stack then.

**Comment by Anton-Latukha** [comment]
Or maybe we can do a clever hack, and form a separate build of executable, but when we ready - the forming executable is a proper way.

**Comment by Anton-Latukha** [comment]
This was done in Nixpkgs quite some time ago, 8.10.1-specific package there provides HNix executable from the last version and onward.
