### ISSUE TITLE
What should NAtom include?

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#657]
Well, I would put it more elegantly.

The discussion is about the above topic, my subquestion I think about is:

1. Should the String type be NAtom? (I nod that it should, since there are no chars in Nix).

2. Should the Context type be NAtom?

3. Should Expression (son of String and Context) be the NAtom? Since without it the NAtom essentially represents only the atomic types, and with it NAtom can embody all Nix language and its internal process. The Expression is an infinitely recursive all embodying son which allows the magnitude of freedom for Nix language to transform itself. Since at times Expression should have the lock to not be interpreted as an Expression (NAtom is an "atom" lock marker), and at times that same Expression would get a proper context alignment and so would be readable to the interpreter. I guess that can be implemented as a separate lock, or Haskell does not need a lock due to purely functional nature and strict typing, without a NAtom, but the discussion should we use the separate abstraction or NAtom directly, because that affects the design of the type system, include we atomic at times and main recursive abstraction into NAtom or not.

**Comment by sjakobi** [comment]
> 1. Should the String type be NAtom? (I nod that it should, since there are no chars in Nix).

AFAICT strings are currently not included in `NAtom` because they can contain interpolated expressions, and therefore don't necessarily evaluate to themselves.

https://github.com/haskell-nix/hnix/blob/220209c09087481e2defefd7ad8b522bb1f56169/src/Nix/Atoms.hs#L21-L24

**Comment by Anton-Latukha** [comment]
Considering this closed.

NAtom indeed seems to represent the end point of evaluation tree.
