### ISSUE TITLE
Please, implement REPL evaluation different styles of multiline Nix epressions

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#665]
REPL handles only single line expressions now.

Sorki reminded and pointed out the cause https://github.com/haskell-nix/hnix/pull/658#discussion_r446095214

Also this addresses the question why I talk that REPL is unusable currenly https://github.com/haskell-nix/hnix/issues/656#issuecomment-650062268.

**Comment by sjakobi** [comment]
Yeah, multi-line support would be cool.

Maybe we can copy some bits from the `dhall repl` update: https://github.com/dhall-lang/dhall-haskell/pull/1867
