### ISSUE TITLE
Please, provide Cachix secret in HNix repository

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#682]
@jwiegley

Please, we have a required action to do for https://github.com/haskell-nix/hnix/pull/681.

---

To use Cachix upload in GitHub CI - HNix needs to provide its Cachix secretKey inside GitHub repository, the same key which is used in the current Travis setup.

The secret key should be stored somewhere by you.

Please, put secret into the repository ([straightforward section of official docs](https://docs.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets#creating-encrypted-secrets-for-a-repository)), please name secret as `CACHIX_SIGNING_KEY`, so it is the same name for the key everywhere, it is the variable name that Cachix expects and so also name wich env interfaces built around it await.

Meanwhile, at the same time waiting for this - I would tailor the merged template config to HNix-specific values.

After those both things - the Cachix would work for GitHub CI. Otherwise, in timeout PR would need to progress without Cachix.

**Comment by Anton-Latukha** [comment]
Found a loophole, Travis CI would be used both with GtiHub CI until former gets provided the Cachix secret.

**Comment by jwiegley** [comment]
@Anton-Latukha Can you e-mail me your GnuPG public key? I'd be happy to send you the secret key.

**Comment by Anton-Latukha** [comment]
Provided, works.
