### ISSUE TITLE
Please, remove from CIs the use of Nixpkgs GHC 8.4.4, since it is deprecated

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#684]
Nixpkgs keeps a promise to deliver last three major versions of GHCs, and 8.4 is currently fourth.

After yesterday's updates in Nixpkgs the GHC 8.4.4 no longer present normally.

It is still present in many Nixpkgs files, but:

```fish
nix-env -f "<nixpkgs>" -qaP -A haskell.compiler | awk '{print $2}' | sort | uniq

ghc-8.10.1
ghc-8.11.20200505
ghc-8.2.2-binary
ghc-8.6.5
ghc-8.6.5-binary
ghc-8.8.2
ghc-8.8.3
ghc-8.8.4
ghcjs-8.6.0.1
```

---

Due to complex merge in the process, I bundled this update into https://github.com/haskell-nix/hnix/pull/681.

**Comment by sjakobi** [comment]
FWIW, I would prefer our GHC support policy not to be dictated by Nixpkgs packaging choices. If it's difficult to have a GHC 8.4 job in our current CI setup, maybe we can extend it to install GHC with [hvr's PPA](https://launchpad.net/~hvr/+archive/ubuntu/ghc), `ghcup`, or `stack`.

**Comment by Anton-Latukha** [comment]
Yes.

Pointed out that Nixpkgs policy is to keep the last 3 GHC versions, so they dropped 8.4 from the infrastructure, so the Travis Nixpkgs builds can not use GHC 8.4 to build stuff, because it is not there.

Replacing the Nixpkgs 8.4 test with the Cabal Hackage test.
