### ISSUE TITLE
"attribute 'neat-interpolation_0_5_1_1' missing" with nix-build

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#687]
At https://github.com/haskell-nix/hnix/commit/7cd6a0f27692a6489d5ba51cbd836a03ad3a44b0 I'm getting a build failure with `nix-build`:

```
$ nix-build --argstr compiler ghc883 --arg buildFromSdist true
building '/nix/store/zy5n6b08n8xfqjg13k6aqbdgfhm8ds05-cabal2nix-hnix.drv'...
installing
error: attribute 'neat-interpolation_0_5_1_1' missing, at /home/simon/src/hnix/default.nix:216:55
(use '--show-trace' to show detailed location information)
```

How do I fix this?

**Comment by Anton-Latukha** [comment]
Maybe the answer is simple. Update Nix channels.

`default.nix` by default use default local channel and its revision.

```fish
{sudo,} nix-channel --update
```

Or use channel description from GitHub directly `--arg useRev true --argstr rev nixos-unstable`.

I've checked, all recent channels evaluate the description, so this is most probably the solution.

**Comment by sjakobi** [comment]
Many thanks, @Anton-Latukha! `nix-channel --update` did the trick.
