### ISSUE TITLE
Please, update optparse-applicative to 0.16

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#692]
Today update was released.

Last time I wrote Haskell I was learning `optparse-applicative`.

So I would take this to the practice.

**Comment by sjakobi** [comment]
Apologies, @Anton-Latukha. I had forgotten about this issue when I made #697. Otherwise I would have left the task to you.

**Comment by Anton-Latukha** [comment]
It was my error taking several tasks at a time, so I am happy you looked into this update.

I still think how much one needs to trust and look into dependency updates. Haskell seems to be very good language to trust updates and we seem to look into updates more then in other languages.
