### ISSUE TITLE
Let clause does not allow inherit line

### ISSUE THREAD

**Issue by bergey** [haskell-nix/hnix#7]
I see a couple ways to fix this, so I'd like some guidance.  

My understanding of Nix syntax is that each line in the variable-binding section of a `let` expression can be a single binding (name = value;) or an `inherit` expression (inherit (set) name1 name2 name3).

The current `NExprF` has `NLet [(r,r)] r`, and a separate constructor for `NInherit`.  This doesn't allow `NInherit` to appear in the first section of the let.

We could rewrite `inherit` expressions in explicit form (name1 = set.name1; name2 = set.name2).  But I think it's nicer to preserve the concrete syntax of the parsed file.  For tools I'd like to write using hnix, where I may be parsing a human-edited file and making changes, rewriting the inherit like this would be unfortunate.  Similarly, (I think) hnix doesn't normalize `some.attr.path.name1 = val; some.attr.path.name2 = val` and 

```
some.attr.path = {
  name1 = val;
  name2 = val;
}
```

So I'd like to see `NLet [Either (r,r) (r,[r])]` or more explicitly:

``` haskell
data LetBinding r = Explicit r r | Inherit r [r]
NLet [LetBinding r] r
```

Does this seem like the right approach?

**Comment by jwiegley** [comment]
That sounds like a good idea to me.  The AST we use needs to be exhaustive, so that we can pretty-print back out exactly what we read in.  I also like the idea of discriminating through types as much as we can.

**Comment by shlevy** [comment]
:+1:

**Comment by bergey** [comment]
Closed by https://github.com/jwiegley/hnix/pull/9
