### ISSUE TITLE
New release (0.4)?

### ISSUE THREAD

**Issue by Profpatsch** [haskell-nix/hnix#70]
There have been a few changes, so maybe it’s time for another release!

A new major version is needed, because the [license changed](https://github.com/jwiegley/hnix/commit/07e9e66bf7169c4e8d34d0bf6dadc3cb7d6f0390).
The [commit implementing `NEnvPath`](https://github.com/jwiegley/hnix/commit/bd39df38b6835cc7a43cf7c72d5c4fc912f9637c) also leads to changes that might surprise some people.

Changelog:
* License change from ? to BSD3
* Correctly parse identifiers with reserved word prefixes
* `mkDot`/`mkDots` automatically quote non-symbols
* Escape `${` but not plain `$` in indented strings
* Add support for `NEnvPath`

**Comment by jwiegley** [comment]
Current master (054eb3c) uploaded to Hackage as 0.4.
