### ISSUE TITLE
CI breakage with "NixOS-unstable channel, GHC 8.6.5" and "Nixpkgs-unstable channel, default GHC (8.8)"

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#706]
Both fail with `error: attribute 'neat-interpolation_0_5_1_1' missing, at /home/runner/work/hnix/hnix/default.nix:229:55`.

See e.g. https://github.com/haskell-nix/hnix/pull/705/checks.

**Comment by sjakobi** [comment]
Seems related to https://github.com/haskell-nix/hnix/pull/680#issuecomment-667522144.

**Comment by Anton-Latukha** [comment]
Solved by #709, where some CI builds were removed and by #708 where `neat-interpolation` Nix package was updated.
