### ISSUE TITLE
Expanding the maintainers team

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#745]
@jwiegley 
For the project growing the maintainers from old tested contributors seems a good strategy of streamlining the project and its cycles.

Can we include @expipiplus1 and @layus into maintainers?

1. Recent merge is shown: #739 - that I am so far not very apt at reviewing harder code cases of experienced people, and that there @expipiplus1 essentially maintains me )

2. And also @layus already politely indicated that: https://github.com/haskell-nix/hnix/pull/744#pullrequestreview-518119115

If it is agreed, further I (or them, since they seem apt) - might grant permissions to people that shown the skill set, adequacy and time invested/stick around, and have pretty direct interest for the project.

For such long-standing experienced contributors as @expipiplus1 and @layus rights granting seems self-evident.

**Comment by Ericson2314** [comment]
I will certainly vouch for @expipiplus1 and @layus in particular :).

**Comment by jwiegley** [comment]
Yes, be my guest @Anton-Latukha! Thank you for asking.

**Comment by Anton-Latukha** [comment]
@expipiplus1 and @layus, `maintainer` invite is sent on your GitHub email. You are free to accept or not accept the invite, it is to your decigion.

**Comment by expipiplus1** [comment]
Happy to chip in :)

**Comment by layus** [comment]
Thanks for the invite, and the recommendations :-).

**Comment by Anton-Latukha** [comment]
Ok, the question is closed, thank you, everybody.
