### ISSUE TITLE
Meta thread for special cases/quirks of the Nix language and discussion/work on them

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#761]
Please document them into: [NixOS Wiki: Nix Quirks](https://nixos.wiki/wiki/Nix_Quirks).

**Comment by Anton-Latukha** [comment]
As put in: https://github.com/haskell-nix/hnix/pull/748#issuecomment-720137535
`nix-shell --pure --command 'hoogle true'`

`shell.nix`:
```nix
attrs@
  { compiler ? "ghc8101"
  , withHoogle ? true
  }:
(import ./. attrs).env
```

`default.nix`
```nix
{ withHoogle ? false }
```

Or:
```
let
  function = args@{ a ? 23, ... }: args;
in
 function {}
# will evaluate to an empty attribute set.
```

Manual states:
> args@ expression is bound to the argument passed to the function which means that attributes with defaults that aren't explicitly specified in the function call won't cause an evaluation error, but won't exist in args.

**Comment by Anton-Latukha** [comment]
- such cases should notify with the message, warning, or the full solution is simple - use of `?` in `@` - should be deprecated, because as it officially put - does not work.

**Comment by Anton-Latukha** [comment]
The reason why one needs to put:
```nix
attrs@{compiler ? "ghc8101", ...}:
```

While as we saw - it does not work, and manual puts it is vacuous, nevertheless, suddenly it provides the most useful side effect - it the only case I know when command argument gets respected and passed into derivation:
```
nix-shell --pure --argstr compiler "ghc884" --command 'ghc --version'
```
Would supply what user asked - `8.8.4`.

How we currently done:
```nix
attrs@{ ... }:
let defaultAttrs = {
  # Defaults are put in this form deliberately. Details: #748
  withHoogle = true;
  compiler = "ghc8101";
};
in (import ./. (defaultAttrs // attrs)).env
```

Surprises with old behavior:
```
nix-shell --pure --argstr compiler "ghc884" --command 'ghc --version'
```
Would supply *not* what was asked `8.8.4`, but what is "default" `8.10.1`.
Old: `attrs@{ ... }:  (import ./. attrs).env` also not passed the arg, what tried to solve in the first place (the main initial reason for the PR).

---

So - it seems like to pass args it needs a default to be set in both places in two ways to work as expected.

```nix
attrs@{compiler ? "ghc8101", ...}:
let defaultAttrs = {
  # Defaults are put in this form deliberately. Details: #748
  withHoogle = true;
  compiler = "ghc8101";
};
in (import ./. (defaultAttrs // attrs)).env
```

Works as expected:, if user asks
```
nix-shell --pure --argstr compiler "ghc884" --command 'ghc --version'
```
It would supply asked `8.8.4`.

And default case:
```
nix-shell --pure --command 'ghc --version'
```
Would supply the default case, `8.10.1`

This form works properly for all cases:
```nix
attrs@{compiler ? "ghc8101", ...}:
let defaultAttrs = {
  # Defaults are put in this form deliberately. Details: #748
  compiler = "ghc8101";
};
in (import ./. (defaultAttrs // attrs)).env
```

This solution is true not only to `compiler` but other args also.

Very strange, this indeed needs to be documented better and accounted for further down the line.

It feels like I am rediscovering this behavior I forgot.

**Comment by soulomoon** [comment]
The case is fixed

```
attrs@{ ... }:
let defaultAttrs = {
  # Defaults are put in this form deliberately. Details: #748
  withHoogle = true;
  compiler = "ghc8101";
};
in (import ./. (defaultAttrs // attrs)).env
```

```
❯ nix-shell --pure --argstr compiler "ghc902" --command 'ghc --version'
building '/nix/store/l4f7n95jl5h50y6pw82jmxhvig4smvq5-cabal2nix-hnix.drv'...
The Glorious Glasgow Haskell Compilation System, version 9.0.2
```
