### ISSUE TITLE
Please, reduce MonadPlus

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#768]
Notices that `<+>` defined in `Parser` is just a `MonadPlus`'s `mplus`, which is a just `Alternative`'s `<|>`.

Special things `MonadPlus` promises over `Alternative`:
  * "is a monad"
  * And:
```haskell
mzero >>= f  =  mzero -- left zero`
m >> mzero   =  mzero -- right zero`
```
As Haskell Wikibook puts it: "If `mzero` is interpreted as a failed computation, these laws state that a failure within a chain of monadic computations leads to the failure of the whole chain."

**The only place that uses `mzero`**:
`Nix/Type/Infer.hs`:
```haskell
instance Monad m => MonadError TypeError (Solver m) where
  throwError err = Solver $ lift (modify (err :)) >> mzero
  catchError _ _ = error "This is never used"
```
, since MonadPlus specificity depends only on that `mzero` behavior with Monad - reducing this use of the law should free up the project from the MonadPlus.

Since `MonadPlus` is vague and gets deprecated in more places,
Please watch where it can be removed with performance preservation, and where it is used, lets explain its use.

**Comment by Anton-Latukha** [comment]
The `MonadPlus` deprecation goes up the stack:
https://github.com/haskell-nix/hnix-store/runs/1712505541?check_suite_focus=true

We better reduce it soon.

**Comment by turion** [comment]
Where is it mentioned that `MonadPlus` will be deprecated?

**Comment by Anton-Latukha** [comment]
> Where is it mentioned that `MonadPlus` will be deprecated?

Ye, I need to own these:

  * From all the reading that I've done about it, and assessing that there is no heads or tails of MonadPlus abstraction, reading the discussions on it and seeing the MonadPlus use and code being reduced. Connected the dots and said that it gets deprecated, well to be fair, it got/gets deprecated everywhere where it can be replaced, except it is not being deprecated officially.

  * On a hunch wrote the https://github.com/haskell-nix/hnix/issues/768#issuecomment-761333705, went upstream, the issue was in `logict` where the MonadPlus interface was touched> and I knew this message was wrong, but never returned to remove or change it.

---

I knew that `MonadPlus` is a more powerful constraint than `Alternative`, so is some cases it may give more performance. But the doubt about `MonadPlus` use dwarfed that memory.  Now I see that MonadPlus is indeed still used on some particular occasions in the parsers where the `(Alternative a, Monad a) => MonadPlus a` constraint allows to give more performance.

With that, since part of the thread was misleading, giving a reformulation to the top post and hiding the https://github.com/haskell-nix/hnix/issues/768#issuecomment-761333705.

**Comment by Anton-Latukha** [comment]
In the end it was established the `MonadPlus` is indeed leveraged properly, in the `Parser`.
