### ISSUE TITLE
Won't nix build

### ISSUE THREAD

**Issue by sorki** [haskell-nix/hnix#792]
At the end of the build during installation phase it fails with:

```
Setup: filepath wildcard 'nix/corepkgs/buildenv.nix' does not match any files.
```

**Comment by sorki** [comment]
I've manage to hit this from https://github.com/sorki/hnix-overlay using `nix-build -A hnix` (possibly caused by `nixpkgs` bump).

**Comment by layus** [comment]
Sometimes files are just missing ;-) https://github.com/sorki/hnix-overlay/pull/2

**Comment by sorki** [comment]
Oh, thank you. That explains why it was working when built locally from branch where it has all the files. Maybe we could carry these few in main repo to make things simple.

**Comment by layus** [comment]
A good idea indeed :-)

Le 5 janvier 2021 18:37:57 GMT+01:00, Richard Marko <notifications@github.com> a écrit :

**Comment by layus** [comment]
Note that the tests also use data from the submodule. Apparently they are silently skipped when missing.

On second thought, I think we should keep the submodule as is and make the error more clear when it is missing

Le 5 janvier 2021 18:37:57 GMT+01:00, Richard Marko <notifications@github.com> a écrit :
