### ISSUE TITLE
Please, support GHC 9.0.x

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#858]
Currenly waiting on the upstream to support GHC 9.0:
```
[__0] trying: hnix-0.12.0.1 (user goal)
[__1] trying: split-0.2.3.4 (dependency of hnix)
[__2] next goal: base (dependency of hnix)
[__2] rejecting: base-4.15.0.0/installed-4.15.0.0 (conflict: split =>
base<4.15)
```
:arrow_up: https://github.com/byorgey/split/issues/9

**Comment by sjakobi** [comment]
The issue with `split` appears to be resolved. Apparently the bound on `hashable` is a blocker now:

```
hnix-0.12.0.1 (conflict: hashable==1.3.1.0, hnix => hashable>=1.2.5 && <1.3.1)
```

**Comment by Anton-Latukha** [comment]
When recently tried to build HNix: [`http-client-tls`](https://hackage.haskell.org/package/http-client-tls) depends on [`memory`](https://hackage.haskell.org/package/memory), which is only up to `8.10`.

Also remembering `hnix-store` having `foundation` as indirect dependency.

**Comment by sjakobi** [comment]
`foundation` and `memory` have compatible releases now.

**Comment by Anton-Latukha** [comment]
`hnix-store-{core-remote}` now compatible with GHC 9.0.

Now indeed can work on HNix GHC 9.0.
HNix GHC 9.0 compilation throws a number of instance errors in `Expr.Types`, connected to Template Haskell deriving a roaster of instances. TH sequencing matters. & there is a pretty careful question with several pieces, seems like there is a bit more to what mentioned in the TH [ChangeLog](https://hackage.haskell.org/package/template-haskell-2.17.0.0/changelog).

**Comment by Anton-Latukha** [comment]
If you would excuse my typo in ChangeLog that called a release WIP - GHC 9.0 is there, HNix 0.14.0 is out.

I stopped ChangeLogging changes, for now.

There are no API changes for DHall projects (which use the `Shorthands` module).

**Comment by Anton-Latukha** [comment]
Well, lets wait on Hackage Matrix report.

**Comment by Anton-Latukha** [comment]
Oh, wait, yes, *afair* Hackage Matrix yet to support 9.0. Well, *"it works"* then.
