### ISSUE TITLE
Please, lets fix the origin of `lookupEnv`

### ISSUE THREAD

**Issue by layus** [haskell-nix/hnix#900]
With #890 and the switch to relude, `lookupEnv` becomes ill defined.

relude exports `lookupEnv` but only starting from 1.0.0. As we have no version bounds on relude in hnix.cabal, the build is broken on some configurations.

**Comment by Anton-Latukha** [comment]
`relude` provides a number of lifted functions/instances, but those `relude` abilities is to do project-wide decigion of their use and would have a locking effect.
So kept the old origin.
