### ISSUE TITLE
Constraint on relude needs to be >= 1.0.0.0

### ISSUE THREAD

**Issue by sternenseemann** [haskell-nix/hnix#933]
Since we depend on relude reexporting parts of `text` and `unordered-containers` we need to make sure we have at least `relude` 1.0.0.0.

**Comment by Anton-Latukha** [comment]
Yes.

Was pretty careful with use of reexports. Library builds great with `0.7` relude, thou before release I cleaned-up the Cabal dependencies, which introduced dependency on reexports provided in `relude`, which indeed were introduced in `1.0`.

To extimate the constraints, checked the bounds introduced to what HNix had. The package bounds are on stable packages and have big timescale bounds, nothing got restricted. Thou it added another structural dependency.

In reality pretty ready to see & evaluate the new base & prelude.
