### ISSUE TITLE
Functions to name and form:

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-nix/hnix#948]
Patterns that need a meticulous name:

```haskell
toValue . f <=< fromValue -- is a frequently used wrapper, transformation from Nix type to Haskell type that can be processed by Haskell function:
-- Great example is @lenth@ builtin:
> lengthNix = toValue . (length :: [NValue t f m] -> Int) <=< fromValue
-- ^ Therefore document `fromValue <-> toValue` & put into introductory course
fromValue{,May} . coerce  -- (fromValue . Deeper) is just one of specialized forms of it
fromValue{,May} @returnType <=< force
fromValue{,May} @returnType <=< demand
addProvenance . Provenance -- `Eval` nv.*P functions should add those which use this patterns & include Provenance constructor into the functions, so just the scope & values are passed
-- > addProvenance (Provenance scope $ NBinary_ span NApp (pure f) Nothing)
-- becomes
-- > mkApplWithProv scope span (pure f) Nothing
-- and
-- > nvClosure (Provenance ..)
-- becomes
-- > mkClosureWithProv scope span ...
```

**Comment by layus** [comment]
Unless I am deepky mistaken, demanding and forcing before calling fromValue is redundant. The pattern is to use fromValue alone. Not sure about coerce without looking at the code, but I see no reason for it to be different.



Le 3 juin 2021 16:06:25 GMT+02:00, Anton Latukha ***@***.***> a écrit :

**Comment by Anton-Latukha** [comment]
So far can not make statements on `fromValue` & `force/demand` strictness for it. `force & demand` relate to strictness & demand analysis & idk if the requirement of materialization of lists & attrSets before doing any operation on them is efficient right here. `force` is the core of this question, & it (besides locking mechanism) does nothing more than:
```
writeRef tValRefV $ Computed =<< (`catch` bindFailedW) =<< readRef tValRefV
```

In its simplicity `force` is still kinda a mystery to me. The main cookery happens in the monad structure. It seems that `force` doesn't force the `v` even into WHNF, but monad evaluation & all of it is proclaimed `Computed`.

But still that regards the `force` & not `fromValue =<< force` reasoning - I still can not say anything definite about it, if anything - would listen on it.

But in any case - these are patterns to abstract & then they would show more meaning.

**Comment by Anton-Latukha** [comment]
To be honest - I am still lost in the type class jumps inside the forest of `Convert` module, it is hard to say if all of them lead to `demand/force`.

HLS jumps to type class definition & does not support jumping to instance implementation, there is no tool that show those instance connections.

---

Seems like `demand` is not always called during conversion:

```haskell
instance Convertible e t f m
  => FromValue Float m (NValue' t f m (NValue t f m)) where

  fromValueMay =
    pure .
      \case
        NVConstant' (NFloat b) -> pure b
        NVConstant' (NInt   i) -> pure $ fromInteger i
        _                      -> Nothing

  fromValue = fromMayToValue TFloat

fromMayToValue
  :: forall t f m a e
  . ( Convertible e t f m
    , FromValue a m (NValue' t f m (NValue t f m))
    )
  => ValueType
  -> NValue' t f m (NValue t f m)
  -> m a
fromMayToValue t v =
  maybe
    (throwError $ Expectation @t @f @m t (Free v))
    pure
    =<< fromValueMay v
```

That `Float` instance `fromValue` jumps into `fromMayToValue` which jumps back to `Float` `fromValueMay`.

---

I'd reformulated the question: where `demand/force` should be used.

But I digress. It would've been great if from the message thread it was possible to create a report.
