### ISSUE TITLE
Compatibility with aeson 2.0

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#991]
If I build `hnix-0.14.0.1` with `--allow-newer=aeson`, I'm getting this build error:

```
src/Nix/Utils.hs:157:18: error:
    • Couldn't match type ‘Data.Aeson.KeyMap.KeyMap A.Value’
                     with ‘HashMap A.Key A.Value’
      Expected type: HashMap A.Key A.Value
        Actual type: A.Object
    • In the first argument of ‘M.toList’, namely ‘m’
      In the second argument of ‘($)’, namely ‘M.toList m’
      In the expression:
        A.pairs
          . mconcat
              . ((\ (k, v) -> A.pair k $ toEncodingSorted v) <$>) . sortWith fst
          $ M.toList m
    |
157 |       $ M.toList m
    |                  ^
```

Some guidance regarding the migration can be found in https://github.com/haskell/aeson/issues/881.

**Comment by Anton-Latukha** [comment]
Thank you.

Ok. Then I would probably need to make (would make) 2 releases (minor branched release to support old release & new major release) in the near time.

**Comment by Anton-Latukha** [comment]
Published https://hackage.haskell.org/package/hnix-0.14.0.2.

**Comment by Anton-Latukha** [comment]
Also note - published another, now major release today - it is a big one (~400 commits), changes that are important to the DHall are in the changelog.
